### ISSUE TITLE
One old feature

### ISSUE THREAD

**Issue by ChuJung** [writemonkey/wm3#102]
In WM2 was feature binded on F3. While this button pushed, WM2 window was minimized, so i can read text in my browser or other window. In WM3 on F3 - search. Is there new button for this feature or WM3 doesn't have it?

**Comment by writemonkey** [comment]
Doesn't have it, but I'll add it for the next release.
i.

**Comment by ChuJung** [comment]
Thank you

**Comment by writemonkey** [comment]
One way or another that can be done with OS features.
i.
