### ISSUE TITLE
View Comments in Preview EXPORT have an problem, if after a "Full-Line-Comment" is not a clearline

### ISSUE THREAD

**Issue by floriandd2ba** [writemonkey/wm3#115]
View Comments in Preview EXPORT have an problem, if after a "Full-Line-Comment" is not a clearline

in short:
````
// Kommentar
## header
<p><div class="block-comment">kommentar</div>## header</p>
````

Solution: RegExp search for new line character, but better is search for carriage return character
Old Preview Code:
`text = text.replace(/^\/{2}(.*?)\n/gm, monkey.localStorage["EXPORT_INCLUDE_COMMENTS"] == "1" ? '<div class="block-comment">$1</div>' : "");`

Fix Preview Code:
`text = text.replace(/^\/{2}(.*?)\r/gm, monkey.localStorage["EXPORT_INCLUDE_COMMENTS"] == "1" ? '<div class="block-comment">$1</div>' : "");`

Long Sample:
```` 
# Test Kommentar

vorher //kommentar inline
## we,flwflr,frewfewrfreferfer


text
//kommentar ohne Abschluss und ohne Leerzeile
## mekerkgrekreg

text
// kommentar mit Abschluss und ohne Leerzeile//
## mekerkgrekreg

text
// kommentar ohne Abschluss und mit Leerzeile

## mekerkgrekreg

text
// kommentar mit Abschluss und mit Leerzeile //

## mekerkgrekreg
```` 

HTML Problem:
````
<p><div class="block-comment">kommentar ohne Abschluss und ohne Leerzeile</div>## mekerkgrekreg</p>
````

HTML View:
<body style="font-size:.8em;>
<div id="wrapper">
<h1 id="test-kommentar">Test Kommentar</h1>
<p>vorher<span class="inline-comment">kommentar inline</span></p>
<h2 id="we-flwflr-frewfewrfreferfer">we,flwflr,frewfewrfreferfer</h2>
<p>text</p>
<p><div class="block-comment">kommentar ohne Abschluss und ohne Leerzeile</div>## mekerkgrekreg</p>
<p>text<br><span class="inline-comment"> kommentar mit Abschluss und ohne Leerzeile</span></p>
<h2 id="mekerkgrekreg">mekerkgrekreg</h2>
<p>text</p>
<p><div class="block-comment"> kommentar ohne Abschluss und mit Leerzeile</div></p>
<h2 id="mekerkgrekreg">mekerkgrekreg</h2>
<p>text<br><span class="inline-comment"> kommentar mit Abschluss und mit Leerzeile </span></p>
<h2 id="mekerkgrekreg">mekerkgrekreg</h2>
</div>
</body>

**Comment by writemonkey** [comment]
Fixed.
i.
