### ISSUE TITLE
View Problem with Code sniplet with 3 backticks

### ISSUE THREAD

**Issue by floriandd2ba** [writemonkey/wm3#119]
If you use 3 backticks before and after a code snipplet, the following text have an other format view in wm3.
For better understanding, please look at the screenshot.

Thanks
![wm3code](https://cloud.githubusercontent.com/assets/26163855/25393426/ba278758-29db-11e7-8099-6b78c07f240d.PNG)

**Comment by writemonkey** [comment]
Already fixed for 3.0.4.
i.
