### ISSUE TITLE
Some Smart characters not working

### ISSUE THREAD

**Issue by Eusorph** [writemonkey/wm3#147]
Perhaps I misunderstood how smart characters work, but if I didn't, some of them don't behave correctly. I was under the impression that when you type one smart charcters, two would appear and let you write inside of them, but this is what I get

"=" (type one get one)
*=*
_=_
/=/
(=() -type one get two with cursor inside-
{ ={}
[={}
<=<>

**Comment by BsNoSi** [comment]
There is a difference in behavior of "smart" and "very smart" characters. Only braces `(` `[` `{` `<` create directly the corresponding counterpart. All others reqire a selection (highlighted block), where i.e. `*` is set around the block.

I tried a little bit around, but it seems to me, that there is no way to add characters to the list or to change a "smart" character to "very smart" or vice versa.

**Comment by writemonkey** [comment]
Fixed. Adding smart characters now work. Also, all pairs are now very smart, even "", '', ** ...

**Comment by BsNoSi** [comment]
Is a new bea with a fix for that in sight?
