### ISSUE TITLE
Beta 4 not opening on MacOS

### ISSUE THREAD

**Issue by diegopau** [writemonkey/wm3#148]
Hi,

I have downloaded it from here http://writemonkey.com/wm3/, opened "Writemonkey.app" and all I get is this window:  
![nw js 2017-09-29 20-16-36](https://user-images.githubusercontent.com/315149/31029718-1f84785c-a553-11e7-8ecf-e6703949855b.png)

The previous version was working without issues.

**Comment by diegopau** [comment]
Solved. I should have looked into this https://github.com/writemonkey/wm3/wiki/Documentation#installation-on-apple-osx-sierra.

**Comment by yashas-vaidya** [comment]
@diegopau, could you elaborate how the link solved the issue for you? I tried the second solution by "using some 3rd party archiving program" (Unarchiver) to unzip the files instead. Still got the same screen as you though.

I'm on high sierra (10.13.3). Don't have access to "some other non Sierra" computer for now. Can try that solution as well.

Thought would be good to document for others as well.
