### ISSUE TITLE
Highlighting Line of Text (Minor Issue)

### ISSUE THREAD

**Issue by not2bryte** [writemonkey/wm3#150]
Hi,

I appreciate the change you made from the previous beta where now 'home' and 'end' move the cursor to the beginning or end of the line as viewed on the screen! 

One minor inconsistency, though. Now when I try to highlight text -- for example, if my cursor is near the beginning of the line and I wish to quickly highlight that remaining line -- I was expecting to be able to hit 'shift' + 'end' (or 'home' as the case may be) as I do in other editors, including WM2. Instead WM3's present beta highlights the remainder of the paragraph, as if it were still treating 'end' as it was in the earlier beta. For consistency's sake, might you be able to have 'shift' + 'home' and 'shift' + 'end' only highlight the screen line?  :-)

Thanks!

**Comment by BsNoSi** [comment]
I do support this wish :)

**Comment by bgnocturnal** [comment]
Hey! I use Shift+Home/End quite frequently, so I'd love for this to get a higher priority.

**Comment by pdxkcm** [comment]
Still busted, 2+ years later. Most other text editors and word processors select from the current position to the beginning/end of the line when you hold down SHIFT and press HOME/END respectively. This inconsistency in WM makes one of the most common navigation techniques a real pain.

**Comment by BsNoSi** [comment]
I gave up and switched to Typora.

**Comment by pdxkcm** [comment]
> I gave up and switched to Typora.

So did I, but Typora has its own foibles. It's tough to find a good, straightforward text editor these days.

**Comment by BsNoSi** [comment]
I regularly find myself using notepad++…

**Comment by bgnocturnal** [comment]
@writemonkey Any updates?

As you can see, for people used to this, the issue is a real pain.

**Comment by writemonkey** [comment]
Ok, I just changed/fixed this. Shift+End/Home now selects from the cursor to the edge of screen line (not paragraph). Next version will be out in a couple of days. I do listen, eventually 😂
i.

**Comment by bgnocturnal** [comment]
Awesome, can't wait! Thanks for looking into this!

**Comment by writemonkey** [comment]
fixed
