### ISSUE TITLE
Tables not rendering correctly

### ISSUE THREAD

**Issue by Caelestis1** [writemonkey/wm3#151]
When I use, or try to use, the git version of markdown to format some information into a table it often doesn't work. When I'm putting in the "-" they often seem to be changed to some shortened form, even if I delete and replace with the correct format it doesn't seem to get recognised as a table properly.

**Comment by writemonkey** [comment]
I guess this is Auto replace plugin causing you problems. Disable it or change "--" trigger in it's package.json file.
i.

**Comment by Caelestis1** [comment]
I had a go at that. Took a backup, removed the bits, tried again no luck. Disabled it, still no luck then hit across the issue by accident. I need a line gap for the table to work (<- crap explanation so let me try a bit better).

Random line of text
<Header1> Pipe <Header2>
Dashes Pipe Dashes
Item1 Pipe Item2
Item3 Pipe Item4

So the above if you replaced the Pipe with | and the dashes with - doesn't render.

However if I do:
Random line of text
<Blank line>
<Header1> Pipe <Header2>
Dashes Pipe Dashes
Item1 Pipe Item2
Item3 Pipe Item4

Then this does render. I don't know if this is by design or not, however at least I can reproduce it! If it is by design just close this down as user error :)

**Comment by writemonkey** [comment]
It seems gfm tables require empty line above them, like in the example below. First table renders, second doesn't.
i.

| Header  |  Header |  Header |
| ------- | ------- | ------- |
| Content | Content | Content |
| Content | Content | Content |

some text
| Header  |  Header |  Header |
| ------- | ------- | ------- |
| Content | Content | Content |
| Content | Content | Content |

**Comment by Caelestis1** [comment]
Yep sounds like thats just how the functionality works. Thanks for looking into it for me.
