### ISSUE TITLE
Issue pasting plain text

### ISSUE THREAD

**Issue by zenpeace** [writemonkey/wm3#152]
Writemonkey 3.0.4 Beta. When pasting plain text at the start of a SCRATCH document I get formatted text in the window. See attached screen capture. Using Windows 10 with latest updates on a Dell Latitude. If I start typing and then paste the plain text, it appears normally in the SCRATCH window.

![image](https://user-images.githubusercontent.com/32717108/31460297-8d4a2436-ae8b-11e7-89ac-a846659878a6.png)

**Comment by writemonkey** [comment]
See: https://github.com/writemonkey/wm3/wiki/Documentation#document-meta-data
i.
