### ISSUE TITLE
Info bar chances only in settings_main?

### ISSUE THREAD

**Issue by BsNoSi** [writemonkey/wm3#153]
I tried to modify my infobar in settings_main_user.jason. This does not work. 

Copying the desired setting to "settings_main.jason" works as described.

> I changed the data storage path. Maybe this leads to side effects like it does with registration (allways stored in local user path).

**Comment by novakwh** [comment]
Data_directory change also did not work in the user file for me, I had to change it in the main settings file. I believe I had this same issue with an earlier beta release.

**Comment by peppo212** [comment]
I also had the issue "Data_directory" does not work in the user file for me". It got fixed by removing comma after the last setting in settings_main_user.json.
