### ISSUE TITLE
New Document Glitch

### ISSUE THREAD

**Issue by LThorburn** [writemonkey/wm3#159]
Since the latest update, every time I add a new file a small thin rectangle appears in the top left corner of the screen a few seconds later. This is usually accompanied by a brief decrease in responsiveness, and occasionally WM has crashed. See below for a picture.

![image](https://user-images.githubusercontent.com/5829453/32529645-bd2569aa-c48d-11e7-963c-8bc9b953501d.png)

Any idea what might be causing this? I'm on Windows 10 and using a custom theme, which I just copied over from the previous installation, if that's relevant.

**Comment by writemonkey** [comment]
If you use one of the original unmodified themes included in this version - does the bug also happen?
iztok

**Comment by LThorburn** [comment]
On further investigation: yes, it does still happen with the original themes for this version.

I've also narrowed it down a bit further. It happens when you create a new document and start entering metadata straight away (eg. 'name: Sample Name') in the first line. It doesn't happen if you type ordinary text in first, even if you then go back and add metadata above it.

Hope that helps! Let me know if there's anything else I can check.

**Comment by writemonkey** [comment]
I managed to recreate the bug as you describe it. Will look into this, thanks!
iztok

**Comment by writemonkey** [comment]
Fixed.
i.
