### ISSUE TITLE
WM2 vs WM3, Open Webbrowser with URL

### ISSUE THREAD

**Issue by Hermann12** [writemonkey/wm3#168]
How can I add an URL for e.g. to some translator pages like google translater, www.pons.eu or Leo.org? In W2 I could create a F1 or FN function, what was really helpful.

**Comment by writemonkey** [comment]
I am not sure I understand. Do you need something that is described here:
https://github.com/writemonkey/wm3/wiki/Documentation#macros
i.

**Comment by Hermann12** [comment]
That could be a solution, thanks! In V2 I used a Right Click and the context menu with Shortcut like FN. Your suggestion works also, Thanks!
