### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by novakwh** [writemonkey/wm3#180]
Kind of nitpicky, but would it be possible to set it up so that the word count doesn't include words in the metadata? For example, if I set both a name and a goal in a document, word count shows 4 words before I've even really written anything, which throws off the word count for the goal -- just a little bit, and it's not really a big deal, but thought I would ask.

**Comment by writemonkey** [comment]
Yes, I'll handle that.
i.

**Comment by writemonkey** [comment]
Done.
i.
