### ISSUE TITLE
Custome Theme File

### ISSUE THREAD

**Issue by ericrobe** [writemonkey/wm3#183]
I created a custom theme. For the most part it works great, I like the integration of CSS elements - great idea. I have run into something I can't figure out how to get around.

As you can see by the attached image, I think I have set the font for the editor in my custom theme but the font size never changes. Using the DevTools I see that my font-size is being ignored. The DevTools allow me to directly edit the Element.Style which does change the font size. Where is my mistake? Why is the font size in my custom theme being applied? I am running 3.0.5 Beta w my donation file

I am using a laptop & depending on where I am, I use different monitors. One has a radically different pixel density than the others. I would like two custom themes - each with a font size best suited fort the monitor I am using.

![20180410-writemonkey](https://user-images.githubusercontent.com/35535634/38588289-17e3969a-3cf3-11e8-9000-436f1114a9e4.PNG)

**Comment by writemonkey** [comment]
Yes, this is a problem. The font size value from theme file is trumped by the current zoom factor. Use CTRL+6 and CTRL+7 to adjust font size. In the future I'll change this so that zoom factor will be relative to the font-size from the theme.
i.

**Comment by ericrobe** [comment]
thanks - that works
