### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by snauth** [writemonkey/wm3#185]
Running wm3 on linux with a high dpi laptop screen (2560x1440) everything is quite tiny. I can increase default font size which helps a lot but I did not find a setting to enlarge everything else. Did I miss something?

**Comment by imatmati** [comment]
Same here with chuwi  at 2736 x 1824. This problem is recurrent with hidpi.

**Comment by writemonkey** [comment]
Noted.

**Comment by writemonkey** [comment]
Done. 3.0.6 will have a setting to change zoom factor of all UI elements.
i.
