### ISSUE TITLE
Monkeywisdom

### ISSUE THREAD

**Issue by preludeinz** [writemonkey/wm3#195]
A lot of the quotes included in the text file for monkeywisdom are misogynistic and/or really tasteless. Basically any search through the source file for the word "woman" or variants thereof pulls up a quote that puts a bad taste in my mouth, personally, and I don't like it when examples like these are the first thing I see when I start up a software that's otherwise brilliant, and has become a cornerstone of my creative process. These are just a handful of examples, some of which are worse than others:

- Why do streamlined girls offer the most resistance?
- My girlfriend is pregnant, so we got the big book of names out. To try and find the dad.
- If you see a man opening a car door for a woman, it means one of two things: new woman or a new car.
- **Nowadays prison is like a walk in the park, you might get raped.**
- Behind every successful man is a woman who wants a fur coat.
- If a man stands in the middle of the forest speaking, and there is no woman around to hear him, is he still wrong?
- **When a woman gives oral sex a hormone is released in her body that burns fat.**
- Science has made many advances, but none so far with women.
- A pessimist thinks all women are bad; an optimist wishes they were.
- If women ruled the world there would be no wars. Just a bunch of jealous countries not talking to each other.

The majority of the quotes in wisdom.txt are harmless, and I realize that it's easy enough to edit the file myself, but I just wondered why include things that are potentially offensive/alienating to what would reasonably be 50% of your users in the first place. A lot of the quotes about writing or the creative process in general are funny and insightful, and for my own part I might put together a file full of writing prompts or basic warm up exercises or something like that, but the quotes as included are really just pretty bad. They're derogatory and alienating. The people I've shown the worst examples to have universally reacted with strong offense, and rightly so. It's the sort of thing that make me feel unwelcome as a user, and which I've complained about to friends. It also deters me from recommending the software to other writers I know, despite the fact that it's easily the best program I've ever written with and I genuinely don't know what I'd use without it. I've used wm3 and its predecessor for years now, written hundreds of thousands of words into it, and I want it to be the best it can possibly be.

Otherwise the software itself has been absolutely fantastic and I'm grateful for and impressed with it every single day. Thank you for all your hard work, I've just updated to the latest beta release and I really appreciate all the little quality of life changes.

**Comment by writemonkey** [comment]
Dear preludeinz,

I had this conversation many many times and it always led down to the rabbit hole. Personally I think those are just stereotypes and most jokes are exactly that. Maybe I don't see this as a problem because I am not misogynist and not a woman. That said, I can see how this can feel wrong for many, so I'll just give up and surrender. If you care you can send me the wisdom.txt file where you put an asterisk in front of every quote you think is inappropriate. Otherwise I will, just to be safe, remove all of those which have a word women in it :)

And thanks for all the nice words about wm, I'll try to make it even better.

i.

**Comment by preludeinz** [comment]
hi!

I really appreciate your reply, and I'm really glad you're willing to make a change. I think the problem with stereotypes like these is that they're really a lot less harmless than they seem, and seeing them in places where one hopes to feel supported and inspired and welcome is really a letdown. I understand that this sort of humour seems like it's easy to take too seriously, but there's a lot of it out there, none of it's good, and it all adds up. It's the sort of thing that just reflects poorly on the program, and the program itself is too good for that. Because writemonkey really is amazing, and I want to be able to recommend it to everyone I know, unreservedly and with a clear conscience.

The degree to which writemonkey became part of my process is almost unbelievable, I would never have expected that I could be come so deeply attached to a program like this, but it’s just so perfectly suited to my needs and I really can't imagine writing without it. I've tried loads of other writing software (zenwriter, focuswriter, scrivener, just to name a few), but I've been with wm and wm3 for three years now and I won't ever go back. This program blows them all out of the water (especially scrivener, which seems so complicated and expensive and somehow not nearly as powerful as writemonkey is, all while writemonkey is free and so simple and intuitive to use). Aside from the issues I had with monkeywisdom, I can’t say enough good things about this program. It’s clever and brilliant and endlessly useful to me. I’m using it to type up this post. I’ve opened it every day for the past three years, I've used it to write dozens and dozens of stories, I've used it to try and teach myself CSS and dabble in a few simple coding projects. There’s hundreds of thousands of words between me and writemonkey. It’s important to me and and it’s become something I have a relationship with. I joined the beta for this newest version because I was so excited to have it, and because I wanted to help give back to the person who’d take the time to make it in the first place, in whatever small way was possible. I really can't thank you enough for all your hard work. 

I think it might be a bit of a tall order to go through the entire file and curate everything according to my own personal metrics, but if that would help, then I can try and find some time. You've put a lot of work into this software and it's valuable enough to me personally that I would like to help try to make it better. I'll attach the file to this ticket when I get done with it.

If I can make another suggestion, some of my favourite quotes of the same type/style come from old [unix fortune files](https://en.wikipedia.org/wiki/Fortune_(Unix)), and these were what I was planning to replace my own wisdom.txt file with. If you were interested in changing out wisdom.txt for something completely fresh, here are a few sources that seem like they could be a good alternative: 
http://fortunes.cat-v.org/plan_9/
https://github.com/shlomif/fortune-mod/tree/master/fortune-mod/datfiles

I was also thinking about compiling a text file of different writing prompts, journaling prompts, and little warm up exercises. I'm not sure when I'll find the time to put those together, but if they're something that would be interesting to you I would be happy to include those as well.

Thank you very much again :)

Cheers,
preludeinz

**Comment by writemonkey** [comment]
Maybe it is time to refresh monkey wisdom. I'd be happy to add an option for users to choose from multiple collections bundled with wm. The default could still be original (yet revised :-) file. I like your idea of thematic collections - writing prompts (maybe quotes on writing from famous writers), journaling prompts, grammar / style tips?? ... but not anything cheesy like inspirational quotes we are seeing everywhere. Also, the collection of reasonably short quotes should be reasonably large so there can always be some surprise left for the user.

So if you happen to compile smth interesting, I'd definitely like to see it.

i.
