### ISSUE TITLE
NW.JS screen when launching on Mac

### ISSUE THREAD

**Issue by vmarks** [writemonkey/wm3#196]
attempting to launch WM3 on Mac causes a few minor stumbling blocks. Here's the steps so far.

1. download wm3 beta 3.0.5 for mac (current OS level 10.12.6)
2. unzip in ~/Downloads
3. launch WM3 by double clicking on the app ~/Downloads/writemonkey3/Writemonkey.app
4. click away dialog box warning that Writemonkey is from an unsigned developer.
5. open system preferences / security, click Open Anyway
6. Writemonkey opens, but only displays a NW.JS browser.

<img width="812" alt="screen shot 2018-05-12 at 11 46 19 am" src="https://user-images.githubusercontent.com/338771/39959064-1f1f1768-55da-11e8-8462-6fc6965a0671.png">

I am not sure how to proceed.

Desired behavior:

steps 4 and 5 could be eliminated if Writemonkey were signed. https://support.apple.com/en-us/HT202491

Step 6: I expected to see a window from Monkey Wisdom and a default document in the Writemonkey window.

Personal note; I last used WM on Windows a few years ago, and liked it very much, especially with the Flesch-Kincaid score option. I've bounced around between editors on Mac, and was excited to see Writemonkey come to Mac. Thank you.

**Comment by writemonkey** [comment]
Hi, this is as close as it gets right now:
https://github.com/writemonkey/wm3/wiki/Documentation#installation-on-apple-osx-sierra
i.

**Comment by njd** [comment]
I'm seeing the same result (just an NW.JS window - that won't quit) using 3.0.7 beta on macOS 10.13.3 (High Sierra).

**Comment by writemonkey** [comment]
Yes, I know, sorry for that, one of the things from this link should help:
https://github.com/writemonkey/wm3/wiki/Documentation#installation-on-apple-osx-sierra--mojave
i.

**Comment by FruitfulDynamic** [comment]
You can create an Alias of the MacOS nwjs file in package contents, put that in your desktop and use that to launch.
