### ISSUE TITLE
Projects in 3.0.6

### ISSUE THREAD

**Issue by novakwh** [writemonkey/wm3#198]
Happy to see projects implemented! At first glance, a couple of initial questions:

-- Will you be implementing sub-folders (or I guess sub-projects)? Important for big writing projects.

-- Is there a way to move an existing document to a project, or do you just need to copy and paste text into a new file inside the project? 

Thanks!

**Comment by writemonkey** [comment]
Hi,
- I am not sure about subfolders.
- You can drag&drop documents to projects.
i.

**Comment by Negreuj** [comment]
I also think it's great to have projects in WM3, so thank you for implementing it! Going further, and endorsing "novakwh", I'd strongly endorse implementing sub-folders as well, if that's possible. Otherwise "projects" tends to get muddled up quite fast.

**Comment by Negreuj** [comment]
How can I take advantage of this feature? Do I need to re-install program? Is there a (new) plug-in for subfolders?
Thank you.

**Comment by writemonkey** [comment]
Hi, subfolders will be available when 3.0.8 is released. 
i.

**Comment by Negreuj** [comment]
Great!<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-green-avg-v1.png"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virenfrei. <a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avg.com</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2018-12-09 10:44 GMT+01:00, writemonkey <notifications@github.com>:
