### ISSUE TITLE
Opening chars injected into document

### ISSUE THREAD

**Issue by philmayes** [writemonkey/wm3#200]
1. Start.
2. At opening quotation screen, type LF LF LF LF.
3. Nothing happens.
4. Type an alpha.
5. Program shows last document upon alpha; 4 x LF AND the alpha are injected into the document.
6. They're all in the undo stack.
7. If just alpha is used, that alone is injected into the document.
8. If mouse is used to enter, all is OK. That's probably why this wasn't caught.
9. Windows 10, WM 3.0.6 Beta - Donkey Kong

I think I've found a writing tool that's close to perfect. I get that exquisite feeling of pleasure at using software that has been properly designed. Thanks!
I'm a new user, so a) I may report bugs because I don't fully understand the program, and b) I'm just the kind of user who discovers bugs via unexpected uses.

**Comment by writemonkey** [comment]
Fixed. Thanks for pointing it out.
i.
