### ISSUE TITLE
If I write first character: '#' in code block (``` ... ```) then get new title in Headings sidebar.

### ISSUE THREAD

**Issue by polyakovDev** [writemonkey/wm3#211]
This screen can explain what I mean. 

![2018-07-25_01-06-07](https://user-images.githubusercontent.com/9868992/43170977-2e384668-8fa8-11e8-9ac7-4f2dc834d935.png)

When I try to escape the '#' character, it appears as '\#'

This is not a critical error, because the text is transformed correctly but sidebar look not aesthetically.
Thanks for this project, it's beautiful)

**Comment by writemonkey** [comment]
fixed.
i.
