### ISSUE TITLE
JS/Csharp/Java comments don't show in previews

### ISSUE THREAD

**Issue by lorddev** [writemonkey/wm3#214]
Example code

* Do not leave out curly braces.

```csharp
  // Correct:
  if (foo != bar)
  {
      throw new BadFooException();
  }
   
  // Avoid:
  if (foo != bar) throw new BadFooException();
  
  // Avoid:
  if (foo != bar)
      throw new BadFooException();
```

I want to see the comments in my preview but they aren't there.

Also, GitHub flavored markdown previews in WM aren't showing syntax highlighting.

**Comment by writemonkey** [comment]
comments must be on in preview.
i.
