### ISSUE TITLE
License issues with Qt?

### ISSUE THREAD

**Issue by ouldskuhl** [writemonkey/wm3#215]
It seems WM3 is violating these obligations of Qt's open source license (see [here](https://www.qt.io/download))

- Must provide a relinking mechanism for Qt libraries
- Must provide a license copy & explicitly acknowledge Qt usage

Are you aware of that? I doubt you're a commercial user of Qt, because that would cost more than $400 per month...

**Comment by writemonkey** [comment]
No such thing in wm3 as it is nw.js (node webkit) based?? Not to my knowledge anyway.
i.

**Comment by ouldskuhl** [comment]
Apologies and thanks for clearing that up - it was a misunderstanding on my side. Of course if you don't use Qt, there are no license issues.

BTW, nw.js is interesting - it means WM3 is actually a browser running an offline web site.
