### ISSUE TITLE
Cannot run on Linux - Antergos  

### ISSUE THREAD

**Issue by raggedmane** [writemonkey/wm3#217]
nw file will not run, regardless of whether I double click it or run it with the terminal.

![error](https://user-images.githubusercontent.com/4885552/43802106-bc946ec2-9a49-11e8-87ef-4573a9c54157.png)

**Comment by writemonkey** [comment]
So it works?

**Comment by raggedmane** [comment]
Got it to work. 
There was an issue with the installation. 
It wouldn't respond to 'npm install', and I had to find a workaround. I should have documented it. Will try to recreate and post here for posterity :)

**Comment by LThorburn** [comment]
@raggedmane Can you remember what you did to get it working? I'm having the same issue.

**Comment by LThorburn** [comment]
Don't worry, managed to get it working. In case anyone else encounters the same problem, I just had to explicitly install the extra/gconf package (that is, the gconf package from the extra repository). In my case it was already installed implicitly as a dependency for another program, but there was an option in the package manager to 'Make install explicit'.

I'm using Manjaro.

**Comment by raggedmane** [comment]
Hey @LThorburn , I just installed Manjaro and am running into the same issue again.
Would it be possible to give me a step by step of what you did after you downloaded wm3.zip file to make it work?

Thanks in advance.

**Comment by LThorburn** [comment]
Hi @raggedmane, it's been a while so I can't remember exactly beyond the specific difficulty described above but it was something like:

1. Unzip the wm3.zip folder somewhere permanent.
2. Using the default manjaro package manager (can be accessed by clicking 'Add or remove software' in the 'Start menu'), make sure that the gconf package is explicitly installed, as described above.
3. Double click on the executable file in the unzipped wm3 folder called `nw`.
4. If that doesn't work, you may need to make the file executable. You can do this by running the following command in the terminal: `chmod +x /path/to/nw`, where you should replace `/path/to/nw` with the relevant path.

As best I can recall that's all I needed to do. Once it's working you can add a shortcut to the start menu.

Hope that helps.

**Comment by raggedmane** [comment]
That worked perfectly. Thank good sir.
