### ISSUE TITLE
Syntax for Footnotes

### ISSUE THREAD

**Issue by BrigitteRath** [writemonkey/wm3#220]
Is there a markdown syntax for footnotes that is supported by WriteMonkey? 

Basically any solution would work for me. This is one existing solution for inline markup for footnotes I found:

This is some text with a footnote.^[Here is the first footnote.] And another ^[Here is the second footnote.]

**Comment by writemonkey** [comment]
Unfortunately, footnotes are a non-standard markdown extension and aren't supported by the parser wm uses. Would love to have them, though.
i.

**Comment by BrigitteRath** [comment]
Thanks for the reply! Just in case and for reference, this here seems a well thought-out suggestion for syntax:
https://github.com/jgm/pandoc/issues/3172#issuecomment-259866410

**Comment by eyeamonlyme** [comment]
+1 for footnotes

I am a historian / journalist and use footnotes for source citations. I hate being tied to MS Word for final edits, footnotes etc. Would be nice if I could export directly from WM and never have to deal transferring content from one platform to another.  However, I know that coding for footnotes would probably be a major project.

**Comment by writemonkey** [comment]
available in v3.0.8
i.
