### ISSUE TITLE
Help: Is it possible to search/replace new line/tab characters?

### ISSUE THREAD

**Issue by ksarnowski** [writemonkey/wm3#225]
I'm editing a finished screenplay to match .fountain format. I'm working in 3.0.7 beta wm3 win64. I need to put a new line (enter) character after names like in an example below. Is it possible to do use some syntax to do it automaticaly? Like in notepad++ by simple search replace "JOHN" to "JOHN\n". I already tried /n, [n] for search/replace without success.
 
example:
From:
JOHN line

To
JOHN
line

**Comment by writemonkey** [comment]
Select JOHN then hit **Alt+F3** to select all occurrences. After that hit **right arrow button** to change selections to cursors (cursors should be at the end oh the john) and then hit **Enter**. You should get:

```
JOHN
line
```

everywhere. 

BTW: You can also select JOHN one by one - by selecting the first, then hitting **Ctrl+D** till every john is selected.

i.

**Comment by ksarnowski** [comment]
Fantastic! Thanks.
