### ISSUE TITLE
Image links not showing coreclty in preview

### ISSUE THREAD

**Issue by ramonskovitch** [writemonkey/wm3#227]
Loving the Beta of WM3, however image links in the preview show as plain text and not a link or actual image. Ordinary URL links are fine.
![image](https://user-images.githubusercontent.com/1908616/50189823-96a40f00-0372-11e9-9b05-2da463fc6f50.png)

**Comment by jmcd040** [comment]
Things I've noticed. (Windows 10 WM3 Beta 8)
Using the format  ![dog]("C:\....") OR format or [dog[("file://C:/...") then hitting F5 will render an image in the edit pane and in the Repository. It doesn't matter whether you use \ or / inside the quotations. HOWEVER the image will NOT appear in the Preview pane nor in any output.
Using ![dog](file://C:/....) doesn't bring in the image anywhere.
This should be marked as a bug and fixed.

**Comment by writemonkey** [comment]
`![](c:/path/path/path/image.jpg)`

At my end this works inline, in preview and on export (testing on Windows 7, Chrome browser, wm3.0.8)
i.

**Comment by jmcd040** [comment]
I agree. Your form of the link works. In fact it's the only form that will work. I can't remember where I picked up the forms using file:// and quotation marks.
