### ISSUE TITLE
Export to html: no images to see

### ISSUE THREAD

**Issue by Alex-T-H** [writemonkey/wm3#230]
On Windows 10 X64 build 1809 the export to html (using IE 11 or Edge) does not show embedded images (picture on a local drive).

**Comment by writemonkey** [comment]
Hi, something like this:

`![](c://path/path/image.jpg)`

should work. It does in preview and in export to Chrome. I can't test IE or Edge right now. Does images show up in Preview?
i.

**Comment by Alex-T-H** [comment]
Problem solved, thanks!

Reason was:
The string was of format
`![](\c:/path/path/image.jpg)`
which was wrong.
Now it does work fine with either
`![](c:/path/path/image.jpg)`
`![](c:\path\path\image.jpg)`


------------------------------------------------
On Wed, 16 Jan 2019 03:16:48 -0800
writemonkey <notifications@github.com> wrote:

> Hi, something like this:
> 
> `![](c://path/path/image.jpg)`
> 
> should work. It does in preview and in export to Chrome. I can't test IE or Edge right now. Does images show up in Preview?
> i.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/writemonkey/wm3/issues/230#issuecomment-454743351


-- 
Axel Hochgraef <a_hochgraef@hotmail.com>
