### ISSUE TITLE
Command palette doesn't open fully

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#233]
WM 3.07 beta 8, 64 bit in Windows 10.
Turn on sound.
Open command palette. Only commands shown are 
Sounds: Start/stop
Edit: Remove New Lines from Selection (undo Hard Wrap)

Cannot access any other commands ever again. Even after deleting the program and recreating all the files from the downloaded zip file!

**Comment by writemonkey** [comment]
Hmm, that is a strange one. So, you can only see those 2 commands and the filter field on the top of palette is empty? What happens if you press let arrow button when palette has focus?
i.

**Comment by jmcd040** [comment]
Pressing the left arrow key makes the palette disappear.

**Comment by writemonkey** [comment]
When you say "Turn on sound", what do you mean? Turn on white noise sound or keyboard sounds? And before that cp worked? Can you provide a screen shot with the palette opened?
i.

**Comment by writemonkey** [comment]
Backspace to delete the selected sound search field? Palette always remembers the last search. You can also just start typing new search/filter.
i.

**Comment by jmcd040** [comment]
I reinstalled WM and haven't had the problem.
