### ISSUE TITLE
Spelling problems with English words ending in "s" 

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#234]
WM 3.08 Beta 8
To make a noun that ends with the letter "s" possessive, English requires an apostrophe after the final "s", for example "the boss' briefcase."
WM3 flags this as a spelling error that cannot be learned by the dictionary system. If I include the apostrophe in highlighting the word and right click to be able to add it to the dictionary, the spelling correction pop-up menu does not appear.

**Comment by writemonkey** [comment]
Fixed with #297
i.
