### ISSUE TITLE
WM3 horizontal rule

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#235]
Placing three dashes  --- creates a horizontal line just fine. However the line **before** it is treated weirdly. It seems to take on the characteristics of a heading without being one. The font is large, it has a drop down arrow and can be collapsed, but does not appear in the left pane index of the document. It is formatted as a heading in the markdown preview. Further any text above it that is not separated by an empty line is formatted the same in the markdown preview, but not in the main edit pane. It's not a critical issue but might bear looking into. Thanks.

**Comment by writemonkey** [comment]
One way to have headings in markdown is:

```
heading1
===

heading 2
---
```

There must be an empty line before --- horizontal line. 
Currently === and --- are not shown in jumps.
i.

**Comment by jmcd040** [comment]
I see. Thanks for the explanation.
