### ISSUE TITLE
Open Directory with Database File - cannot select

### ISSUE THREAD

**Issue by Alex-T-H** [writemonkey/wm3#236]
If the command is selected from the command palette, then an file explorer window opens and I can navigate the file tree. However, there is no button to select the target folder.

**Comment by writemonkey** [comment]
I am not sure what do you mean by "However, there is no button to select the target folder."
All this command do is to show you where are the db files. You can only change the location in settings file.
i.

**Comment by Alex-T-H** [comment]
Thanks, that was my misunderstanding.
