### ISSUE TITLE
Setext creates "undefined" headers

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#239]
I tried using a plugin for Microsoft word called Writage that exports Word documents into md files. It created headers 1 & 2 with equal signs and dashes in the following line. However the document outline in the left-hand pane shows a lot of "undefined" words as this shows
![image](https://user-images.githubusercontent.com/44679831/53098629-4c115100-34e1-11e9-9625-edfd244b883d.png)

**Comment by writemonkey** [comment]
True, it will be dealt with.
i.

**Comment by writemonkey** [comment]
fixed.
i.
