### ISSUE TITLE
There is a problem with dragging the center/right pane boundary in Windows 10

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#241]
WM3 Beta8 bug:
Using Windows 10 laptop with external monitor. WM is on the external monitor; the laptop is set as Window's primary monitor. Using WM3 Beta 8.
I click on the boundary between the Preview Pane and the center edit pane and drag the boundary left or right while holding down the left mouse button. Then I release the mouse button. After that, whenever the mouse cursor passes over the boundary, it behaves as if the move hadn't finished. The cursor will momentarily change to the double bars and the boundary will move slightly - every time I pass the cursor over it. The only way to stop this behavior is to "grab" the boundary (getting the cursor to change to the double vertical bars) with a long depress of the left mouse button, drag the boundary and while carefully holding still, release and then click the right mouse button.
Further, when I try to move the boundary to the right, it is often stubborn meaning it only moves a small amount and stops while I keep moving the cursor. I have to go through the above procedure a few times until I can maintain control of the boundary and the movement is responsive and behaves as I would expect, that is it goes as far as I want and finishes the move action when I release the left mouse button.

**Comment by writemonkey** [comment]
This bug is documented - see:
https://github.com/writemonkey/wm3/wiki/Documentation#preview-plugin
(last paragraph)

It is a strange one due to the way preview window is implemented.
i.

**Comment by jmcd040** [comment]
Got it. That works for me.
