### ISSUE TITLE
Backup notification box is too small for some paths.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#243]
Re: WM3; Windows 10
I moved the backup location to  `C:\Users\Jim\Documents\AppRef\_WriteMonkey3_Backup. `
When I do a database backup this path runs off the right side of the notification box rather than be folded or condensed. You could cut it into several lines at any `\`, for example

`C:\Users\Jim\Documents\`
`AppRef\_WriteMonkey3_Backup`

**Comment by writemonkey** [comment]
I love when bugs are easy to fix :)
i.
