### ISSUE TITLE
Ctrl+H does not execute 'replace all'

### ISSUE THREAD

**Issue by Alex-T-H** [writemonkey/wm3#244]
From the command palette, the command 'replace all' does work fine.
The command palette suggests that the keyboard combination CTRL+H would trigger the same 'replace all'. It doesn't, but triggers the 'replace' dialog in which every instance is replaced after a confirmation.

What is the correct keyboard combination for 'replace all'?
Maybe replace the 'CTRL+H' in the command palette with the correct one.

**Comment by jmcd040** [comment]
I'd like to suggest that the replace function be improved in two ways:
Add "All" button.
Add the ability to use the keyboard to select Y,N,A for yes, no, all rather than only allowing mouse input.

**Comment by writemonkey** [comment]
fixed. no improvements yet though.
i.
