### ISSUE TITLE
Improve cancellation of a search operation

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#248]
WM3 Beta8 Suggestion: Cancelling Search Results: 
After searching for text, all the found items are highlighted. To cancel the highlight, you have open the search dialog (Ctrl+F), delete the last search (Ctrl+Backspace) and hit return.

It would be nice to have a one key/click way to do that. Perhaps the search could place an icon in the bottom status line that indicates an active search and if clicked upon, cancels all the highlighted search results and deletes the last searched text.

**Comment by writemonkey** [comment]
You can use `Ctrl+1` (once or twice) to hide highlight. The command is used to search (toggle) all occurrences of the word under the cursor.
i.

**Comment by jmcd040** [comment]
I see. . That helps. Thanks

**Comment by jmcd040** [comment]
Thanks. That wasn't obvious to me, but it works.
