### ISSUE TITLE
Keep quotes from including the following line

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#249]
Currently quotations always include the line following the end of the quote. However I think this behavior is not consistent with the rest of text handling. If I move text to the line following a quotation, it becomes part of the quotation and I have to spend time undoing that. Again that is not consistent with the handling of other text elements so I keep forgetting that it will happen when I'm moving text around. Can this be changed?

**Comment by writemonkey** [comment]
This is a part of the markdown syntax. Quote must end with an empty line.
i.
