### ISSUE TITLE
Image handling can use significant improvement/fixing

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#251]
WM3 Beta 8; Windows 10; Chrome
This may be a known issue but local image handling just doesn't work well. 

These two forms will place an image into the edit pane of WM3:
`![Ice Crystals]("file://C:/Users/,,,/2013-01-17-039a.jpg")`
`![Ice Crystals]("C:\Users\,,,\2013-01-17-039a.jpg")`
BUT there is no image in the preview or browser output; the text is just passed through.

These do NOT work at all:
`![Ice Crystals](file://"C:/Users/,,,/2013-01-17-039a.jpg")`
`![Ice Crystals](file://C:/Users/,,,/2013-01-17-039a.jpg)`

The last line is in the form given in the WM3 documentation.

In addition, it is not possible to drag an image from Windows Explorer and drop it in WM3.

**Comment by writemonkey** [comment]
New markdown parser (3.0.8) treats local image links differently. You don't need `file://` at the beginning, you just use full path like:

`![](c:\path\path\image.png)`

on Windows or

`![](/path/path/image.png)`

on Mac.

I'll update the documentation. Drag and drop shouldn't be to difficult to implement.
i.

**Comment by jmcd040** [comment]
Just tried it and there are two issues:
As far as placing an image in the WM edit window:
     `![](c:\path\path\image.png)`  does _not_ work using the WM3 Beta8 dowload in Windows 10, however
     `![]("c:\path\path\image.png")`  _does_ work.

_Neither_ form places an image in the preview and browser. The exact text of the link is all that appears.

**Comment by writemonkey** [comment]
Try using forward slashes (/). Does this show the image in browser?
i.

**Comment by jmcd040** [comment]
**No** form of the image link that references local images will make an image appear in the preview or browser.

These forms _will_ place the image in the editor pane:
`![Ice Crystals]("C:\Users\Jim\Pictures\Background Textures\2013-01-17-039a.jpg")`
`![Ice Crystals]("C:/Users/Jim/Pictures/Background Textures/2013-01-17-039a.jpg")`
`![Ice Crystals]("file://C:/Users/Jim/Pictures/Background Textures/2013-01-17-039a.jpg")`

What's common is that the entire contents of the parentheses must be inside double quotations. 

Now this produces good html that loads a picture:
`![dummy][img1]"Image title/attribution or whatever you want to go under it"`

`[img1]: http://placekitten.com/400/300`

but the local image references just copy the entire markdown to the output as text.
