### ISSUE TITLE
Bug in highlighting text.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#254]
WM3 Beta8; Windows 10
There is some weirdness I've noticed in highlighting which you can see in the attached capture of the edit pane. The highlighting of one or two character words does not terminate correctly.  The highlighting is not applied to them or it terminates at the next `==` termination in the same paragraph.

These errors in highlighting do NOT appear in the preview pane and browser. They are rendered correctly there.

![2019-02-28-11-19-51-9967577](https://user-images.githubusercontent.com/44679831/53588700-d04f7e00-3b4a-11e9-876f-196aca560e5c.png)

**Comment by writemonkey** [comment]
fixed
