### ISSUE TITLE
Save repository item to project.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#255]
It would be nice to have the option to link a repository item to the current project so it's available to all files in the project, so the choices would be project, local, global. The user would"unlink" it from the project by selecting "local" or "global."

**Comment by writemonkey** [comment]
What about right click on repo search field and select Current project? This gives you similar result.
i.

**Comment by jmcd040** [comment]
I just tried that after reading your note. Whatever that does, it was confusing. I have two projects with 3-6 files in each with repository items associated with each file and a few global ones. I assume that "Current Project Snippets" should show me all the repository items for all the files in the current project, but it doesn't. It shows me a subset of them and even a subset of the ones associated with the currently selected file. It also shows one snippet from the other project. Whatever it's doing isn't clear to me.

**Comment by writemonkey** [comment]
Hmmm, on a quick test it works fine on my side. The view should show all snippets that were created in any doc from the project. Global snippets except those created in the project are not shown.
i.

**Comment by jmcd040** [comment]
There is no question that the association of snippets with projects does not work as you describe. For example, I have two projects. In Project B there are 4 files. 
File 1 shows 8 snippets including a global one. File 2&3 show the global snippet. File 4 show the global one and two others.
- If I'm looking at File 1 and search for `%` instead of 8, I see 4 snippets (also while viewing any file in Project A): The global one disappeared; one from a file in Project A appeared; one from the fourth file in Project B appeared; two remained.

I've been trying features as I discover them, so I created files and snippets then tried out projects and then tried to move snippets around by making a snippet global, then going to the file in another project and making that snippet local thinking that the snippet would now be associated with that file and no longer be associated with the file it was created in. Perhaps your database has become confused as a result of this?

**Comment by writemonkey** [comment]
My bad, you are right. The project view only works for snippets created with newer versions that support projects. Older snippets are not shown in that view. Thanks for pointing this out.
i.

**Comment by jmcd040** [comment]
I've run into something related to this thread. Is there a way to see the project's repository items AND all the global ones? 
I have 12 global items (11 clickable and 1 text).If I select `%` for search, I only see some of the global items (number depends on which project I'm in) along with the project's items. If I use the default selection for repo items, I see all the global ones, but of course only the items associated with the document I'm editing.

**Comment by writemonkey** [comment]
I changed the behavior so that all global items are displayed along with project snippets.
i.

**Comment by jmcd040** [comment]
look forward to trying it.
