### ISSUE TITLE
Bug: Image markdown does not use title attribute

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#259]
WM3 Beta8
I notice that at [github](https://github.github.com/gfm/#images) and [daringfireball.net](https://daringfireball.net/projects/markdown/syntax#link) the form `![Alt Text](URL) "Title text"` would produce code `<a href="URL" alt="Alt Text" title="Title text">` but WM3 would produce `<a href="URL" alt="Alt Text"> "Title Text"` thus placing the title text as normal text after the image, not in the image title attribute. Is that a bug?

**Comment by writemonkey** [comment]
I don't think that:

`![Alt Text](URL) "Title text"`

is valid markdown syntax. Anything outside `![]()` is just a regular text.
i.

**Comment by jmcd040** [comment]
You are absolutely right. I'm sorry I got that wrong. The title text needs to go inside the parentheses. And it works just fine that way.
