### ISSUE TITLE
UI does not change from outline to document view when changing projects

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#260]
WM3 Beta8; Windows 10
Condition: 
-The "Documents" pane open. Two projects are shown, each containing 2+ documents, some of which are bound to external files. One project is selected and one file in that project is being edited.
-The outline  of that document is being shown.
Action: Select the other project.
Results:
- The new project is selected as expected and the contents of the first document in the new project replaces the previously shown document in the edit pane.
- Bug: **The outline does not change. It continues to reflect the previous file being edited. So the outline shown is *not* the outline for the document in the edit pane.**  I would expect the outline pane to change to show the document list for the project selected.

**Comment by writemonkey** [comment]
fixed.
i.
