### ISSUE TITLE
Suggestion: Remove from trash

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#264]
Unless I've missed it, there is no way to remove a document from the trash and put it back into use. I suggest you add the ability to "Remove from trash" and/or drag and drop to a project.

**Comment by writemonkey** [comment]
Right now if you re-save the file in trash it will reappear in the doc view.
i.

**Comment by jmcd040** [comment]
I tried it. Here's what I saw.
- Create a new document (unbound) and enter a few words.
- Move the doc to trash. It disappears from doc pane and when I select Trash it is there.
- While in "Trash" right click on document and move to trash. It disappears from view.
- Click on "All". The file is not in the document list.
- Click on "Trash" and voila, there it is again.
I could not find a way to get it out of "Trash" prison.

**Comment by writemonkey** [comment]
Added menu item to restore deleted documents.
