### ISSUE TITLE
Database doesn't backup automatically

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#265]
WM3 Beta8; Windows 10
In settings_main_user.json, I included `"backup_database_automatically": 1` to backup automatically every hour. I minimized the program, went away for several hours, came back, maximized WM3 and 
opened the command "Application: Database: Backup Database" which said the last backup was 3 hours ago, which is when I did it manually. It doesn't appear the program is backing up the database on its own but I could be misunderstanding something. Could you help me understand this?

**Comment by writemonkey** [comment]
The way it works right now: the back happens at the exact moment when wm is minimised if time is up. So if you just leave wm minimised it won't happen ... until minimisation is done again.
i.

**Comment by jmcd040** [comment]
So the comment in the settings .json file might read `After x hours, do a database backup when the user minimizes wm`
I tend to leave the program maximized all the time since I use multiple Windows Desktops and have one for just for my writing projects.
Would you consider doing a backup regardless of minimized or maximized state?

**Comment by writemonkey** [comment]
Yes.
i.

**Comment by writemonkey** [comment]
Made a small adjustment here: wm will backup database (if due) on *focus lost* instead on *minimize*. It will also keep the previous backup files so 2 backups are saved.
i.
