### ISSUE TITLE
Apply markdown formatting for tasks shown in the outline pane

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#266]
I hope you don't mind the stream of suggestions. I'm throwing out ideas you might want to consider as I encounter them in using the program.

I like the task list in the outline pane. I created a task like this: `- [ ] ==This is a valid task!==` to highlight it with background color. However I notice that the task in the left pane shows the literal markdown with the equal signs. It would be nice to have it highlighted the same way the marked text is in the edit pane.

**Comment by writemonkey** [comment]
Done. All jump items are parsed.
