### ISSUE TITLE
Don't include single or double quote marks in spelling errors.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#267]
Suppose I quote a book:  "the usual connecting phrase, 'and immediately', we are...." The words 'and' and 'immediately' get flagged as spelling errors. The same can occur when quoting someone who quotes another:  "She said 'Don't say that.'"  'Don't & that' will get flagged as spelling errors when they should not.

**Comment by writemonkey** [comment]
I fixed this ... and hoping I didn't break something else maybe for some other language.
i.

**Comment by jmcd040** [comment]
Looking forward to the next release.
