### ISSUE TITLE
Prevent web links being opened in the application 

### ISSUE THREAD

**Issue by snoozysoft** [writemonkey/wm3#270]
I accidentally managed to drag a link to a website into the Writemonkey window whilst researching a topic and due to the nature of how this application was made, it ended up replacing the entire window with that website. Whilst I could press Backspace to get back to Writemonkey, the UI didn't load properly and required me to forcefully close the program through Task Manager before it would re-open again.

**Comment by writemonkey** [comment]
Hi, was that a windows LNK file you dragged into wm?
i.

**Comment by snoozysoft** [comment]
No, if I remember correctly I accidentally dragged either a plaintext link or a logo that redirects to the link when clicked into it.
