### ISSUE TITLE
I think I broke WM3

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#275]
I don't know Javascript very well and perhaps shouldn't have fooled with it. Could you help me undo this?
I created a macro because I have a lot of footnotes to make. The idea was to highlight a book citation and call the macro to turn it into a footnote. I didn't know how to replace the original citation with the created footnote form so I was willing to leave it in the clipboard and paste it manually. However I permanently changed something in WM3 Beta 8 (Windows 10) the first time I tried it.
```
/* Make Footnote */

var e = _editor;
if (e.somethingSelected()) {
	var q = e.getSelection();
} else {
	var q = e.getValue();
}
q = "[^fn]  [^fn]: " + q;
var clipboard = gui.Clipboard.get();
clipboard.set(q, "text");
```
So this almost worked. However the `^fn` in the document is now underlined. Not only that but anywhere `[^` appears the text inside the brackets is underlined and anytime I type `[^` the caret and any following text up to the closing `]` will be underlined. This now happens *in any document*, not just the one I was working in.
I quit and restarted WM (several times) and it still works that way. Should I reinstall WM? Did this reveal a bug of some sort?

**Comment by writemonkey** [comment]
Text inside brackets is technically a link. In a theme file that you are using, there is a definition:

```
$wm-link {
	text-decoration: none;
	font-style: italic;
}
```

it must contain `text-decoration: none;` in order for footnotes not to be underlined. First check if that is the problem.
i.

**Comment by writemonkey** [comment]
Also, you can use:

`e.replaceSelection(q);`

instead of clipboard approach.
i.

**Comment by jmcd040** [comment]
text-decoration is none. 
The underline only showed up after I executed this macro.

**Comment by writemonkey** [comment]
Hmm, I did try your macro and it didn't underline text inside brackets. It worked as intended. I can't see how that would happen because of the macro, especially after restart. 

Does all themes underline?
i.

**Comment by jmcd040** [comment]
Now that you mention it. no. Only my current theme which is a modified beige theme.

**Comment by writemonkey** [comment]
:) I thught so, was just writting:

Then there must be a syntax error somewhere before`$wm-link` and rules after it are skipped. Send me the theme and I'll have a look.
i.
