### ISSUE TITLE
Headings numbers wrong

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#276]
WM3 Beta8 Windows 10  Regarding the numbering of headings in the document (left) pane.
Copy the following into a new document:
```
# H1
## H2
### H3
#### H4
# H1A
## H2A
### H3A
#### H4
# H1B
## H2B
### H3B
#### H4
### H3C
#### H4C
```
then look at the heading numbering in the left document pane. What I see is that the numbering for the H2s restarts after each H1, but the H3's continue. The H4s continue, but then restart after the last H3.

**Comment by writemonkey** [comment]
Playing around and liking this one:

<img width="279" alt="Screenshot 2019-03-25 at 21 44 07" src="https://user-images.githubusercontent.com/4973443/54952998-88ecbf80-4f47-11e9-96b4-fce2c50e0214.png">

**Comment by jmcd040** [comment]
Looks much cleaner. I'd skip the leftmost dot. I'd rather not waste the screen space, but I can see you might want the number of dots to match the heading number. I don't find that necessary, but that's me. Either way, this is an improvement in clarity.

**Comment by writemonkey** [comment]
Removed heading numbering in jumps so this is kind of fixed.
i.
