### ISSUE TITLE
Command Palette gets stuck

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#277]
I brought this up once before but wasn't able to reproduce it until now.

Use Ctrl+Space to open the command palette
Type Sound, Return
Search field is blank, palete now shows choices of sounds.
Type Theme, Return
The palette only shows the word Theme. No selections are shown under it.
Hit backspace to erase "Theme" and the sound options are shown.
The only way to get back to anything previous to sounds is to close the palette and reopen it.

This isn't a critical, but unexpected.

BTW, it would be consistent if the command palette closed when clicking once in the document text instead of twice, since clicking once anywhere else closes it. Again, not critical but helpful.

**Comment by writemonkey** [comment]
When in second level of the palette, hit left arrow key to jump back to the first level.
i.

**Comment by jmcd040** [comment]
That works.
