### ISSUE TITLE
Allow double click in the document/headings pane

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#280]
WM3 Beta8 Windows 10
Another improvement suggestion.
I would find it more efficient to be able to double click on items in the document/headings pane to do the following:
1. Expand or contract the headings for a file in addition to using the little icon for that purpose.
2. Expand or collapse (fold) a heading within a file (and have it remain that way when returning to the headings view of the file either after program restart or viewing another file).

**Comment by writemonkey** [comment]
Added number 2 and fixed auto saving folded regions, collapsed regions and bookmark data.
i.
