### ISSUE TITLE
Beta 9 unbind file is very dangerous

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#284]
WM3 Beta 9
Thankfully you added a dialog for unbinding a file, but it's use is very dangerous. You open a pop-up that has "Confirm" at the top and has "Yes" or "Cancel" options without any explanation of what will happen.
- If the user selects "Cancel" and I think also if the  x to close the dialog, the document is unbound and the file is left on the disk.
- If the user selects "Yes" the file on the disk is deleted.

Both of these actions are good options as was requested in previous issues, but you really need to have an explanation in the dialog box of what the choices mean. "Cancel" usually means just forget the whole thing and do nothing. In your implementation, I don't thing there is a way to actually cancel the operation. I hope you will improve these options. Perhaps "Unlink Document and Keep File" and "Unlink then Delete File" Or you could title the dialog "Unlink Document" and label the buttons "Keep File" and "Delete File."

**Comment by writemonkey** [comment]
I see. On osx the message is visible but on win only partially or not at all. Will be fixed.
i.

**Comment by writemonkey** [comment]
Fixed.
i.
