### ISSUE TITLE
WM3 Beta 9 Failure

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#286]
Re Beta 9 in Windows 10. Window was maximized, but not in WM full screen mode.
I had this happen before and neither you nor I could reproduce it, but I just lost a bunch of work due to it. I created a new document without binding to a file. I was copying material from the web into the document and putting links to the web pages in too.

I don't know what I did, when I clicked something in WM3 and suddenly the entire WM3 window became a window showing one of the web pages I had a link to in the document. When I closed it WM3 went away. I tried restarting it several times and when I clicked Yes on the Windows dialog asking if I wanted to allow the program to run, that dialog went away and nothing else happened. Eventually I discovered that WM3 was a running task (and it won't allow multiple instances) so that's part of why I couldn't restart it. I killed the task but WM3 still won't start. I'm going to re-install it.

This is a case where a true timed automatic backup would be helpful. I'm under a deadline so the time involved is painful.

---
update:
I reinstalled everything and reloaded all my user modifications (settings, templates, themes, sounds) then accidentally broke it again. I think I did something different from the last time, but this time I noticed what I did. I created a heading (h2) that was a web link in the form `[xxx](yyy)`. In the heading pane, that heading was rendered as a link. When I clicked on that heading in the heading pane, the entire WM3 window either became, or was overlaid with a window that showed that web page from the web, or at least part of it. When I killed that window with the upper right hand red x button, all of WM3 went away. This time I immediately went to the task manager and killed the WM3 task. I was then able to start the program again without losing anything.

**Comment by writemonkey** [comment]
Thanks, I'll disable those links in jumps.
i.

**Comment by writemonkey** [comment]
Links disabled.
i.
