### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by LordMcFly** [writemonkey/wm3#290]
-The ability to have an image in the background, similar to Focus Writer (I hope it's not taboo to talk about competitors)
-A visual indicator of any sort that the repository is active
-A prettier integration of the jumps window (like in those screenshots from the mac version)

Thanks for your consideration ! Writemonkey will always be the best.

**Comment by writemonkey** [comment]
Hi, 
- it is already possible to have image for background. See old typewriter theme. If you want image to only cover editor part, move:

~~~
background-image: url(themes/paper3.jpg);
background-size: cover;
background-repeat: no-repeat;
~~~

from `$wm-ui-general` to `$wm-editor`.

- What do you mean by Repository is active?

- Win version should be identical to OSx.

i.
