### ISSUE TITLE
WM3 Strips all background color when printing

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#291]
WM3 Beta9 + Winddows 10
I was disappointed that in Beta 9 preview.js you still loaded wmColorsCSS after templateCSS in the  function getHtml() thus overriding some of the user template with your own. I've changed the order so my template takes precedence but I'd rather not do that on every update. 

A much bigger issue for me is that you strip out all background color when printing. As much as I like many features in WM, this one will cause me to abandon it. I need background colors in my print-outs (which I usually do through a PDF file so I can add a header and footer) for highlights, blockquotes and some in-line <span> formatting and whatever else I'd like.

Have I set something wrong and forgotten what I did? Will you change this?

**Comment by writemonkey** [comment]
Yes.
i.

**Comment by writemonkey** [comment]
Fixed.
