### ISSUE TITLE
Error in the Typewriter CSS template ?

### ISSUE THREAD

**Issue by ogechter** [writemonkey/wm3#293]
Hello ! Nice Beta, like ever ! I'm very happy to work this it.

Juste a small issue I detected in the CSS template named "Typewriter" : the parenthesis are replaced by slash : 
i.e. ( ) -> / /

It's a little bit enoying for communication with my publisher. 
I've test some other templates (not everything anyway) and I've not detected this issue again
Chears
O.

**Comment by writemonkey** [comment]
This is a font issue. Slashes are used instead of parenthesis. Have no idea why.
i.

**Comment by ogechter** [comment]
Strange. So you mean that you would have to update the font to solve the issue ?
so bad.
As a luck, there are plenty of nice template to work with in the meantime. Thanks for that.
rds
Olivier

**Comment by writemonkey** [comment]
Yes.
i.
