### ISSUE TITLE
Wordnik no longer works

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#296]
I get a pane with the little circular arrow at the bottom, but no content. For the last week, I was getting definitions but no more, now I don't get any content. My internet access is working. Any ideas?

**Comment by writemonkey** [comment]
It seems Wordnik made some changes to its APIs.

In plugins/Wordnik/wordnik.js in line 127 change:

`options.includeRelatedTypes.replace(/\n+/g, '')`
to
`options.includeRelatedTypes.replace(/\s+/g, '')`

so "n" must be changed to "s".

Also in plugins/Wordnik/package.json set

`includeReverseDictionary` to false as this feature doesn't work any more. It will be available again, though. (according to Wordnik)

i.

**Comment by jmcd040** [comment]
That worked! Thanks,
