### ISSUE TITLE
Word with single tick flagged as spelling error.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#297]
'Part' is flagged as a spelling error. So is 'Part as in 'Part 1'

**Comment by Gerard-RvE** [comment]
Isn't this a duplicate of #267?

**Comment by jmcd040** [comment]
Yep, you're right. I forgot about reporting it 4 months ago. I use WM frequently and still seeing all these kinds of items flagged as spelling errors is distracting.

**Comment by Gerard-RvE** [comment]
Agreed that it's very distracting. I use it for writing academic articles, and in my references titles are in quotation marks. Spell checker is absolutely worthless there. Therefor remembered this was already reported.
