### ISSUE TITLE
WM 3.0.9 overwrites file changed in other PC!

### ISSUE THREAD

**Issue by cie78** [writemonkey/wm3#300]
I opened a file I had edited in another computer, with another instance of the same version, and WM replaced it with a blank file!
When I opened WM, it reported via a red dialog on the welcome screen inside the window that the file I had been working on (in a Dropbox-synched folder) had been changed by another instance of WM. Then, when I clicked on the screen, it only showed an empty SCRATCH file!  If it had not been for Dropbox's new history feature, I would have lost all the data on that file! 
I understand now that one should be careful with Beta software, but this is truly shocking! You need to correct this ASAP!

**Comment by writemonkey** [comment]
Fixed.
