### ISSUE TITLE
WM 3.0.9 metadata not recognized

### ISSUE THREAD

**Issue by peggysah** [writemonkey/wm3#301]
I am not sure if this is an issue with the documentation (and thus is just user error) or if this is a bug with the metadata not being recognized. I've created a new document and included the following as the first two lines, and saved the document.

```
:tags snippets characterhistory
:goal 10000
```

The documents panel does not change, searching by `#snippets` returns no results, and there is no progress bar on the bottom.

**Comment by writemonkey** [comment]
You should use:

~~~
tags: snippets characterhistory
goal: 10000
~~~

i.

**Comment by peggysah** [comment]
Ah, user error. The easiest/hardest kind of error to solve. Thanks!
