### ISSUE TITLE
Beta 10 font went away

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#307]
After installing Beta 10, the font I used for my custom theme, Segoe UI seems to not to be the font in the main edit window any longer. I didn't change anything in my theme file. Here's the entry I use in the theme file:
``
$wm-ui-general {
	background-color: var(--main-background-color); 
        font-family: "Segoe UI", Arial, sans-serif;
	background-image: none;
	opacity: 1;
	background-size: cover;
	background-repeat: no-repeat;
}
``

I decided to go back to Beta 9 to get my font back. Let me know when this is fixed or how to fix it.

**Comment by writemonkey** [comment]
This changed. See:
https://github.com/writemonkey/wm3/wiki/Documentation#fonts--line-spacing
i.

**Comment by jmcd040** [comment]
Didn't work. I changed my user settings file in Beta 10 as prescribed by adding "Segoe UI" to the main_font_list. I quoted the wrong part of the css file previously. Here's my editor font spec excerpt
``
:root {
	--editor-font: 'Segoe UI' ;
wm-editor {
	font-family: var(--editor-font);
	font-size: 100%;
	line-height: 1.5em;
	height: 100%;
	background: transparent; 
	color: var(--main-text-color);
}
``
It didn't use Segoe UI. Again, I went back to beta 9 so I can.

**Comment by jmcd040** [comment]
I see. You moved the specification of the font from the theme css file to a menu selection.  I was in a hurry and missed that at first.
