### ISSUE TITLE
Can't open August beta

### ISSUE THREAD

**Issue by novakwh** [writemonkey/wm3#310]
On Mac Mojave; have tried all three of your suggested install fixes and nada -- run from terminal does nothing, others just open a nw.js window when writemonkey.app is run.

**Comment by antman313** [comment]
same here. a nw.js window is coming up :(

**Comment by writemonkey** [comment]
Hmm, I just re-downloaded on Mojave, unzipped in a fresh folder and used (with my local path):

`sudo xattr -r -d com.apple.quarantine /Users/Josip5/Unzip2/writemonkey3/writemonkey.app`

in terminal. After that 3.0.10 starts normally. Will do some more tests.

Did 3.0.9 work on Mojave?
i.

**Comment by novakwh** [comment]
Ok, I must have typed something wrong the first time I did the terminal quarantine thing -- I just re-downloaded it and used the terminal suggestion and now the application opens fine. Thanks.
