### ISSUE TITLE
f5 always formats to table if two vertical lines are present

### ISSUE THREAD

**Issue by Gerard-RvE** [writemonkey/wm3#316]
Although the preview table function is highly helpful, it overrides the collapsing of ranges if two vertical lines are present. For example, see below the same paragraph twice, first normal and then "collapsed" as a table:

![](https://i.imgur.com/K9DBhlP.png)

This is especially annoying when I have bits of code in my text (which are prone to containing multiple | characters) which I would like to hide because to take up a lot of space on my screen. However, they just get reformatted a bit. Is there any way to stop Writemonkey from recognizing them as tables?

**Comment by writemonkey** [comment]
Will look into this.
i.

**Comment by Gerard-RvE** [comment]
Thanks! In the meantime I'm using `ctrl + h` to replace the vertical lines with the Yen symbol before collapsing. When exporting I replace them back. Not a great workaround, but acceptable for the time being.

**Comment by writemonkey** [comment]
fixed
