### ISSUE TITLE
Spellcheck bug

### ISSUE THREAD

**Issue by peggysah** [writemonkey/wm3#327]
Bug I found with spellcheck. I'm writing a novel with non-English names so I've been adding words to the spellchecker. When a word is learned, the possessive form is still always recognized as a spelling error i.e.

Learned word: `nonenglishname`
Spelling error: `nonenglishname's`

**Comment by jmcd040** [comment]
I've noted this too. The spell checker doesn't handle possessive forms very well.

**Comment by writemonkey** [comment]
fixed
