### ISSUE TITLE
Keyboard shortcuts selecting preceding text

### ISSUE THREAD

**Issue by oldjove** [writemonkey/wm3#330]
WM 3.0.10 -- I've noticed that typing Ctrl + I, or B, etc affects (selects and formats) all preceding text in a paragraph. Is that intended behaviour? If I'm writing and hit Ctrl + I to italicize the next word, I end up deleting the whole paragraph. Am I missing something?

**Comment by writemonkey** [comment]
Without selection ctrl+b and ctrl+i (...) will mark whole paragraph. You must select to mark words or sentences.
i.

**Comment by oldjove** [comment]
Ah I see. I'll have to get into the habit of using markdown for the inline formatting. Thanks.
