### ISSUE TITLE
Word Count counts "##" in front of headings as words. (bug)

### ISSUE THREAD

**Issue by jweickm** [writemonkey/wm3#332]
From the second level heading onward, the "##" are counted as words (see picture).

![#count](https://user-images.githubusercontent.com/57487288/69904973-1a051780-13ae-11ea-9380-e8dfa19a7a3d.png)

Hope this can be fixed. 
Cheers, 
Jakob

**Comment by writemonkey** [comment]
FIxed for the 3.11
