### ISSUE TITLE
Documents within folders not saving order

### ISSUE THREAD

**Issue by ChroniclerEnigma** [writemonkey/wm3#334]
when deciding which chapters come before or after another, order is unsaved. Drag and drop does not save when I leave the folder to go to another, or when I leave the program for a moment; I return to see them in the previous disorganized order they were before. Saving does not work. I’ve labeled 1 2 and 3 via the headings and the field name value suggestion, but it will continue to place chapter 2 after 3 and 5 after 6. 
Is there anyone else encountering this Issue? is there any fix?
my operating system is windows 10.
This version I have not yet paid for the plugins, but I plan to. I have paid previously for writemonkey 1 plugins, and I quite enjoyed them.

**Comment by writemonkey** [comment]
fixed
