### ISSUE TITLE
Word count is wrong if there is a hyperlink

### ISSUE THREAD

**Issue by Torsten-K** [writemonkey/wm3#335]
The word count (also character count) counts incorrectly if there is a hyperlink in the text, no matter if formatted in Markdown or HTML Syntax. The words/characters in the whole paragraph are not counted.

`![Writemonkey](https://www.writemonkey.com)`
or
`<a href="https://www.writemonkey.com">Writemonkey</a>`

Xubuntu 19.10, 64-bit

**Comment by writemonkey** [comment]
fixed

**Comment by Torsten-K** [comment]
Hey, great news, thanks for fixing!
