### ISSUE TITLE
Data file size increases by factor 3 after install of v3.0.10

### ISSUE THREAD

**Issue by Alex-T-H** [writemonkey/wm3#337]
After Upgrade from version beta9 to 3.0.10 the file size of "writemonkey3_sheets" increased by a factor of three. 
(Installation on Windows 10 Version 1909  OS build 18363.535)

This looks as if the efficiency of file size has decreased with the newer version.

Please check if this is a bug that increases the file size without need for.

**Comment by writemonkey** [comment]
Nothing changed from 9 to 10 in that regard. Check if

`"keep_document_undo_data": false,`

is set to false in settings file. Also compact the db via command palette.
i.

**Comment by Alex-T-H** [comment]
compacting the db did reduce file size to what I expected.

Thanks!
