### ISSUE TITLE
Multiple Cursor Exit

### ISSUE THREAD

**Issue by BTCarpenter** [writemonkey/wm3#339]
When using multiple cursors `alt + click drag`  how do I exit multiple cursors? 

`esc` does exit multiple cursors but it also toggles fullscreen

Maybe an inconsistency?

**Comment by writemonkey** [comment]
You just click on the text (without any modifier key) to get single cursor again.
i.

**Comment by BTCarpenter** [comment]
Gotcha, that makes sense too. Just curious if there was a keyboard shortcut 😃
