### ISSUE TITLE
Indented second paragraph is painted in theme accent color

### ISSUE THREAD

**Issue by alpersunter** [writemonkey/wm3#341]
Try typing this:
Lorem ipsum dolor sit amet, [ENTER][TAB]consectetur adipiscing elit,[ENTER][ENTER]sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

How it looks on my computer:
![image](https://user-images.githubusercontent.com/41203420/72662604-2135c280-39fa-11ea-840c-9b0c8d483692.png)

**Comment by writemonkey** [comment]
Hi, this is intended markdown behaviour as tabbed line between empty lines is a code line and translates as <code></code> in HTML.
i.

**Comment by alpersunter** [comment]
Alright, my bad. Thank you!
