### ISSUE TITLE
How to add page numbers in PDF export?

### ISSUE THREAD

**Issue by jweickm** [writemonkey/wm3#349]
I have tried to adjust the output CSS to include page numbers with
```
@page {
  @bottom {
    content: "Page " counter(page) " of " counter(pages);
  }
}
```
but to no avail. Is there a way to print page numbers on PDF documents directly?

**Comment by jweickm** [comment]
In Writemonkey 2 we had "print from preview". Maybe something similar would be great. Although I never really liked the page numbers being pushed so far into the corner of the page.

**Comment by writemonkey** [comment]
Hi, print from preview is available in ver3 too, but as a plugin  available to donors.  @page rule is very limited and won't do what you want.
i.

**Comment by jweickm** [comment]
Hi, thank you for your quick reply! 
Is this (see screenshots) what you meant? As a donor I also have access to the plugins, but the 'print from preview' window looks quite different than the one in wm2. Sorry for the Japanese language, but it should be visible that there is no option to select the header and footer in wm3, whereas it existed in wm2. 

Is there any chance that printing page numbers will come to the next update? Or how does everybody add page numbers? 

![print from preview wm3](https://user-images.githubusercontent.com/57487288/79558116-f2d08d80-80a3-11ea-9ec5-063052cb28d3.png)
![printer dialog wm3](https://user-images.githubusercontent.com/57487288/79558117-f3692400-80a3-11ea-8a4a-256286856426.png)
![print from preview wm2](https://user-images.githubusercontent.com/57487288/79558120-f401ba80-80a3-11ea-9c24-f571139c2cfc.png)

**Comment by writemonkey** [comment]
I see, choose Open in browser and then print from browser, where you can set headers and footers.
Iztok

**Comment by jweickm** [comment]
Alright, that makes sense. I just thought I had missed something as it was possible to do that directly from the print menu in wm2. Thanks for the quick responses!
Jakob
