### ISSUE TITLE
Wordnik Plugin not working

### ISSUE THREAD

**Issue by jweickm** [writemonkey/wm3#350]
I have the same issue as described [here](https://github.com/writemonkey/wm3/issues/296). 
Did Wordnik make changes to their API again?

**Comment by andycyca** [comment]
I believe so. The [docs](https://github.com/writemonkey/wm3/wiki/Documentation) mention: 

> **Recently Wordnik changed their API policy which limits number of API calls per single key. If you are using this plugin frequently consider applying for your own free API key at <https://developer.wordnik.com/>**
