### ISSUE TITLE
Unable to use spaces instead of tabs

### ISSUE THREAD

**Issue by pdxkcm** [writemonkey/wm3#352]
There appears to be no setting to use spaces instead of TAB characters, or else I missed it.

A quick perusal of writemonkey.js yielded this:

```javascript
function setCM() {
  // Codemirror default options
  var opt = {
    //...
    indentUnit: _settings.tabs_number_of_spaces,
    tabSize: _settings.tabs_number_of_spaces,
    indentWithTabs: true,
    //...
```

So it looks like I can adjust the number of spaces per TAB, but I can't just insert spaces instead, since `indentWithTabs` is hard-coded to `true`.

It would be highly preferable to be able to be able to control whether WM inserts spaces or TAB characters.

**Comment by writemonkey** [comment]
Hi, version 3.2 has:

```
"indent_with_tabs": true, 
"tabs_number_of_spaces": 4,
```

in settings and indentWithTabs is not hardcoded.
i.

**Comment by pdxkcm** [comment]
Verified, thank you!
