### ISSUE TITLE
can't find documents // collapsed ???

### ISSUE THREAD

**Issue by jojaMB** [writemonkey/wm3#354]
hello.
don't know if it's correct to call it documents, but the window between
vDocuments
vProjects
and where you write, i must've clicked it away, because now i can't see it or interact with it.
how do i un-collapse it?

[apologies for the poor choice of words, i don't know a lick of coding or coding language.]
thanks :-) -NMB

**Comment by writemonkey** [comment]
Click left most edge od the window to toggle visibility of  documents/projects pane.
F9 will do the same thing. Is this it?? 
i.

**Comment by jojaMB** [comment]
yes, thank you! :-D
was worried i'd have to reinstall the whole thing for a sec haha
thanks again, and have a good rest of your day :-)
-NMB
