### ISSUE TITLE
Unable to use custom fonts

### ISSUE THREAD

**Issue by slidepoetry** [writemonkey/wm3#359]
Just upgraded to 3.2, running on Windows 10 64 bit. Managed to restore most of my settings/themes but have been unable to use any custom fonts. The fonts are installed on my PC, and worked in the previous version of WM I was using (believe was 3.0.1). I tried adding two families to the main font list of the settings (in the user settings json) but neither will show up as an option in WM after restarting. Double checked spelling for both font names (Adobe Caslon Pro and Arial), double checked that both are installed.

Not sure what I'm missing here but any help would be very much appreciated. Thank you!

[settings_main_user.zip](https://github.com/writemonkey/wm3/files/4664115/settings_main_user.zip)

**Comment by writemonkey** [comment]
Hi you have {{ }} in your user settings file. There should be only one pair of brackets - at the beginning and at the end. See settings_main.json for the correct structure.

Also it is a good practice for settings_main_user.json to contain only those settings that are different from default values.
i.

**Comment by slidepoetry** [comment]
Thanks so much for the help, managed to get it working! Very glad I chose to support this program.
