### ISSUE TITLE
Can't export a certain sentence

### ISSUE THREAD

**Issue by Lorhelei** [writemonkey/wm3#369]
I found that when trying to write:

<Before after time,

Wen exporting there was no text. 
After some tests I realize that if there's a word after a "<" simbol, it will ignore it, but only if it's a certain words ( I don't know about others)

In case of "Gracias." for example, isn't necessary to add that space before. Furthermore, adding a "dot" (.) at the end make some words to been able to be exported correctly

Is this a bug or something I'm not getting in? 

In order to reproduce it: 

Writing: <Before after time.>
Text exports **incorrectly**

Writing:  <Before after time>
Text exports **correctly**

Writing: <Time after Before>
Text exports **incorrectly**

Writing: <Great Animal>
Text exports **incorrectly**

Writing: <Great>
Text exports **Incorrectly**

Writing: <Great.>
Text exports **Correctly**

Writing: <Gracias.>
Text exports **Correctly**

Edit: I realize that is because <---tags--->, so, the question is, how can I get around this? It works sometimes and I just can't say if whatever I write will be there after exporting.  

![image](https://user-images.githubusercontent.com/26716570/87141483-f7967f00-c257-11ea-9230-17d941aadd40.png)

**Comment by writemonkey** [comment]
`<http://some.com>`

is a syntax for markdown links, so I'm sure this is causing problems. If url is not well formed, parser will skip that part. 

Using spaces like:

`< some text >`

will always work.
i.
