### ISSUE TITLE
Parsing error with Preview

### ISSUE THREAD

**Issue by nc-ulille** [writemonkey/wm3#376]
I have a problem with this kind of markdown text:
`[link1](http://something) and [link2](http://anything)`

When I click on "Preview: Export to Default Browser" or "Copy as Clean HTML", it strips the first URL and the text between:
`<a href="http:anything">link1</a>`
It seems to be related to the "/"

Any ideas?

**Comment by writemonkey** [comment]
Can't reproduce this, even when switching `Include comments` on and off. Are you using the latest release (3.2.0)?
i.

**Comment by nc-ulille** [comment]
You're right. I upgraded from previous version, and it disappeared ! Thanks.
