### ISSUE TITLE
Nothing at all happens when I activate spellcheck ## Version 3.2.0 (April 2020)

### ISSUE THREAD

**Issue by tomasrei** [writemonkey/wm3#377]
Hi!
After adding the swedish (sv) .dic and .aff from https://github.com/wooorm/dictionaries to my lang folder AND selecting it AND activating it with f7 - nothing happens.

The preinstalled english seem to work and I tried german, which seem to work as well.

Actually, after looking twice I noticed that 3 random words are underlined in red. They are however spelled correctly (except the word wikipedia). To be clear: there tons of spelling mistakes and english words in the document.
Any advice?

**Comment by writemonkey** [comment]
Hi, try this version. 
i.
[sv_SE.zip](https://github.com/writemonkey/wm3/files/5145878/sv_SE.zip)

**Comment by tomasrei** [comment]
Great! That works. Many many thanks!
