### ISSUE TITLE
Some problems with images

### ISSUE THREAD

**Issue by tomasrei** [writemonkey/wm3#379]
Hi! Some issues with images it seems like.

First, if you paste online jpg address in the repository it just displays a blank snippet. If you drag it to the document it inserts the proper code+link. It doesn't display in the preview panel - but is displayed if I use "open in browser".

Secondly, if I use a file-path on my hard drive - it just adds the text without conversion, meaning that if I add the following address to the repository it displays the address **as is**: C:\Users\username\Documents\Statsvetenskap II\Perspektiv på politik HT20\Studielitteratur\hall_taylor.jpg **becomes**:
```
C:\Users\username\Documents\Statsvetenskap II\Perspektiv på politik HT20\Studielitteratur\hall_taylor.jpg
```

Finally, the above address won't work but if I put it on my desktop or my microSD for example. 
Like this is ok:
```
![image text](C:/Users/username/Desktop/hall_taylor.jpg)
```
this also works (D is microSD-drive):
```
![image text](D:/hall_taylor.jpg)
```
but not this:
```
![image text](C:/Users/username/Documents/Statsvetenskap II/Perspektiv på politik HT20/Studielitteratur/hall_taylor.jpg)
```
Maybe it something to do with permissions?

**Comment by writemonkey** [comment]
Hi, replace spaces in paths with `%20`. So this should work:

C:\Users\username\Documents\Statsvetenskap%20II\Perspektiv%20på%20politik%20HT20\Studielitteratur\hall_taylor.jpg

i.

**Comment by writemonkey** [comment]
You can also use repository macro below to replace spaces with %20 in selected text - i.e. URLs:

``` javascript
/* Replace spaces with %20 */
var e = _editor;
var m = wm;

function r(t) {
	t = t.replace(/ /g, "%20");
	return t;
}

if (e.somethingSelected()) {
	var t = r(e.getSelection());
	e.replaceSelection(t, "around");
} else {
	m.showNotice("Nothing selected!");;
}
```

**Comment by dercar2** [comment]
Hi. I have similar problems. When you insert the image address on the local disk  into the repository, it is inserted as a note with a link in the text. WM doesn't recognize the address as img.

If you register it manually` ![]()` and then insert the image address in parentheses - everything is ok.

I can capture a video.

Example of an address:  c:\Users\dercar\Downloads\yuop.jpg
