### ISSUE TITLE
I did something with the settings but I don't know how to reset?

### ISSUE THREAD

**Issue by DecoGecko** [writemonkey/wm3#385]
I think I did something but I don't know what, maybe a wrong swipe of the trackpad, but now only one third of the screen has words, like super long margins. How do I fix this?

**Comment by writemonkey** [comment]
Hi, this might help:
https://github.com/writemonkey/wm3/wiki/Documentation#font-size-and-text-area-width
i.

**Comment by DecoGecko** [comment]
Thank you so much!
