### ISSUE TITLE
Open settings_main_user.json from command line [Mini Feature Suggestion]

### ISSUE THREAD

**Issue by jweickm** [writemonkey/wm3#398]
Suggesting a very small feature:
It would be cool, if we could open the settings_main_user.json from a command in the command line. Like: "Edit User Settings" or something like that. It would then open directly in WM3 or in the default .json editor.

**Comment by writemonkey** [comment]
Implemented for the next release.
i.

**Comment by jweickm** [comment]
Awesome! Cool and thanks again for the continued support. I'll make sure to buy another license when the next update goes live.
