### ISSUE TITLE
Make heading text larger when using sextet headings. 

### ISSUE THREAD

**Issue by loudandskittish** [writemonkey/wm3#40]
First off, let me say that the WM 3.0 beta has exceeded my expectations. I expected it to be as slow as other Electron-based apps but instead, this is actually faster than a lot "native" text editors I've used. 

Also, I think it's incredible that you support folding sextet headings (I haven't seen another folding Markdown editor pull it off, aside from Markdown Mode in Emacs) 

But I do have one small complaint. When making a sextet heading (which I find more aesthetically pleasing than having hash signs everywhere), the equal signs or dashes become huge while the actual text remains the same size. Would it be possible to also increase the font size in this situation? 

Thank you.

**Comment by writemonkey** [comment]
Thanks, it should be possible to style actual heading and not dashes. I'll look into that.
i.
