### ISSUE TITLE
Wordnik lookup shows words in alphabetical order

### ISSUE THREAD

**Issue by jweickm** [writemonkey/wm3#400]
Hi, when looking up synonyms of words with the Wordnik plugin, the synonyms are shown in alphabetical order. This is an issue because in this way, I only ever see synonyms starting with either the letter "a", "b", or "c". 
Does anybody know a quick solution for this?
Many thanks, 
j

**Comment by writemonkey** [comment]
Wordnik changed significantly since last plugin update, so the list of words is less relevant and bloated. You can open package.json file in plugins/wordnik dir and change maxHitsPerType parameters to some bigger number.
i.

**Comment by jweickm** [comment]
Thanks for the quick reply. Yes, that is unfortunate. This makes wordnik much less useful than before, but the fix that you suggested should provide a decent solution for now.
