### ISSUE TITLE
crashes on mac

### ISSUE THREAD

**Issue by Strayl1ght** [writemonkey/wm3#41]
I'm on a MBA, El Capitan. First time I opened the beta for mac it worked 10 minutes before it crashed. When I open it again, it launches the welcome message screen and some new theme every time, then immediately crashes again. So I can't open WM3 anymore on this version.

**Comment by writemonkey** [comment]
Did it crash out of the blue or at some specific task/command? If it keep crashing, try deleting database files:

`/Users/[user]/Library/Application Support/Writemonkey 3/writemonkey3_sheets`

and

`/Users/[user]/Library/Application Support/Writemonkey 3/writemonkey3_repository`

i.

**Comment by mykolan** [comment]
I have similar problem on El Capitan. WriteMonkey works fine (howewer, i worked less than 10 minutes). But after saving the scratch app does not launch until i delete database files.

**Comment by writemonkey** [comment]
When you save and  wm crashes at next launch, does _writemonkey3_sheets_ contains any data or is it empty. If you can, plese send me _writemonkey3_sheets_  file after the crash.
Thanks,
i.

**Comment by writemonkey** [comment]
Also, is it possible to open Dev tools (Cmd+Shift+J) after the crash? Is there an error notice?
i.

**Comment by writemonkey** [comment]
Ok, I managed to reproduce described crash on OSX. Will publish fix ASAP!
i.

**Comment by writemonkey** [comment]
Also reproducible on windows :(

**Comment by writemonkey** [comment]
Fixed!

**Comment by Strayl1ght** [comment]
Thanks! Do I wait for a new build to show up somewhere or how do I try out the new version? cheers.

**Comment by writemonkey** [comment]
Re download from the links already provided!
i.
