### ISSUE TITLE
Poor performance with large files

### ISSUE THREAD

**Issue by Kensai2000** [writemonkey/wm3#43]
Seems to freeze with a file of of approximately 105k word length when trying to do any function. Some functions, such as "fold all" will cause the application to quit.

**Comment by writemonkey** [comment]
Please send me the file in question, so I can check the exact same circumstances.
thanks

**Comment by writemonkey** [comment]
Also: does having jumps open affect the performance?

**Comment by Kensai2000** [comment]
It seems to be mostly an issue of loading the file into memory. It takes a moment, during which the app is not responsive. If focus is on a large file when the app is loading then the load, which is already a bit more than I'd like, seems to take longer than a functioning app should to become responsive. I've attached the exact file I've been using to test with, though I doubt there's anything particular about it. Once it loads, it seems to perform just fine, whether or not jumps is open. The hiccup just occurs when switching to it or other, similarly sized files.

[Star Wars - Incarnations.txt](https://github.com/writemonkey/wm3/files/322093/Star.Wars.-.Incarnations.txt)

**Comment by writemonkey** [comment]
Improved.
