### ISSUE TITLE
URI slashes break comment styling

### ISSUE THREAD

**Issue by archetyped** [writemonkey/wm3#46]
If a URI is included in a comment, then the URI's double slashes (e.g. `http://domain.com`) will break the styling.  The default editor styling is used instead of the comment styling.

Example:

```
//uri: http://domain.com/
```

**Note:** The text still appears to be recognized as a comment, as it is listed in the jump list, but the styling is broken.

**Comment by writemonkey** [comment]
fixed.
i.

**Comment by jmcd040** [comment]
What version is this fixed in? I think I'm using 3.o.10 and it's still broken. BTW how to I get WM3 to tell me which version it is?
