### ISSUE TITLE
Word Cloud — Problems with German Umlauts

### ISSUE THREAD

**Issue by BsNoSi** [writemonkey/wm3#51]
![image](https://cloud.githubusercontent.com/assets/2784683/16173150/74fb7f46-3598-11e6-81ac-606f56d1bb15.png)

1. "öschen" should be "löschen"
1. "ückgängig" should be "rückgängig"
1. "textgröß" should be "textgröße"

Seems as if first/last letter before/after a german umlaut is lost. See "einfügen" (below "cursor") → this is the correct spelling, same with "auswählen" (left below "auswahl").

**Comment by writemonkey** [comment]
Yes, this a problem with a library that parses words from text. There is the seme problem with some other languages with extended unicode characters. Will look into it. That said, all current plugins, word cloud included, are still very raw.

**Comment by writemonkey** [comment]
This plugin has been discontinued!
