### ISSUE TITLE
no font subpixel antialiasing

### ISSUE THREAD

**Issue by zoggop** [writemonkey/wm3#54]
In Windows 8.1. An enlarged comparison image of Writemonkey 3's (looks like grayscale) vs Writemonkey 2's antialiasing (default cleartype):

![wm3-wm2-antialiasing-enlarged](https://cloud.githubusercontent.com/assets/1203828/16346069/47a65ef6-39fa-11e6-88d4-89e69ce96ee2.png)

I assume this has to do with its web rendering engine. Is there a CSS font smoothing property that's compatible with it, that could be added to a theme?

**Comment by Kensai2000** [comment]
Enhancements in this area would not go unappreciated. Noting that I'm still using the MacType renderer, I feel that WM3 is already better looking in the niggling little details than WM2, but still gives a bit of ground against things like SublimeText or most iOS apps (I am running WM3 in Windows on a Surface 3, so my pixel density is Retina-class and my absolute screen quality is somewhere between an iPad Air 2 and an iPad Pro 9.7", so better than the iPad 4 and iPod Touch 6 I currently have access to so there should no negative hardware disparity in my comparisons; my cheap Windows laptop with its 1366x768 res screen, obviously, causes WM3 to suffer much more noticeably at the hands of Sublime, which I have been using almost exclusively for the last several months).

**Comment by writemonkey** [comment]
I found the problem with subpixel rendering on Windows. It seems that subpixel rendering is replaced by grey scale rendering if filters are applied over wm view port. Even if filters are applied with their default values (wm does that at startup).

That said, I still prefer grey scale rendering (not so sharp) over subpixel on my low res screen. But that's just me. 

I'll deal with that, thanks for pointing it out.
i.

**Comment by writemonkey** [comment]
To disable filters (and enable subpixel rendering) in current build, open Dev tools - `ctrl+shilft+J` and select Resources tab. Within it expand `Local storage` on the left and select `file://`. Find `VIEWPORT_FILTERS` setting and give it value `none`. Restart wm.

Is rendering now up to par?

**Comment by zoggop** [comment]
yup, it looks good now #nofilter ;-)

**Comment by Kensai2000** [comment]
Yes, its very much in parity with expectations set by Sublime. Small but noticeable improvement on my low def laptop screen and much larger bump on the 1920x1280 screen of my Surface. I've got a 23" 1080p monitor that kinda splits the difference, maybe a bit soft in one mode or a bit jaggy in the other, so its more of a mood thing at that point, though almost universally prefer the sharper rendering there.

Thanks.
