### ISSUE TITLE
jumpy command palette scrolling when using up/down arrow keys

### ISSUE THREAD

**Issue by zoggop** [writemonkey/wm3#55]
If I open the command palette and open "View: Set Themes and UI filters", the list of themes and filters is large enough to need to be scrolled. If I use the up/down arrow keys to navigate it and change direction from up to down or down to up, the visible portion of the list jumps. If I move down the list with the down arrow, and then press the up arrow in the middle of the list, the list jumps downwards to show the bottom of the list. If I then press the down arrow, the list jumps upwards to show the top of the list.

**Comment by writemonkey** [comment]
Already done. The fix will be available with the next release.
i.
