### ISSUE TITLE
possibility of themable panes?

### ISSUE THREAD

**Issue by zoggop** [writemonkey/wm3#56]
> Themes only affect editor area. Document pane, module pane + some other elements (like command palette) are not affected by them.

Is this set in stone? Would it be possible to add the feature of themable panes with CSS? At the moment the only way to have a dark-themed UI is by using filters, which also affect images.

**Comment by Kensai2000** [comment]
I prefer the inverted Jumps/Project Management panel to the standard, but applying Invert causes the subpixel antialiasing to be switched off for grayscale antialiasing, which isn't a worthwhile tradeoff, IMO. Ideally, though, I'd like to have an almost completely black screen (or sometimes an almost completely off-white screen), so getting the ability to do that on purpose would be great.

**Comment by writemonkey** [comment]
Done.
