### ISSUE TITLE
Feature Request: Footnotes/Commenting

### ISSUE THREAD

**Issue by Guptal** [writemonkey/wm3#57]
I would love to see a feature that enables the writer to add footnotes to what is written. I like to reference sources/comment and this would be most useful. If the footnotes could be stored on a pane, so as to not get in the way of the text (like in CriticMarkup) that would be most delightful.

**Comment by Atulin** [comment]
Something akin to Google Docs comments? Where you can mark some text, add a comment to it, and the comment is being displayed besides the actual text?

Yeah, that's be a very welcome addition.

**Comment by writemonkey** [comment]
Using `//` at the beginning makes the paragraph a comment. This is not that much different from what you are proposing.

**Comment by Guptal** [comment]
I was thinking more of something along the lines of Microsoft Word's way of outputting comments/footnotes. See: http://i.imgur.com/h5FqB30.png

I like the way it looks, like you're reading a book. Of course, since text in a digital file can span over more than a single page if pagination is not included, it would make sense to have the footnotes appear in a pane instead of at the bottom (since there may not be any bottom to your text).

**Comment by writemonkey** [comment]
Oh, you mean footnotes. That is something I am considering.
i.

**Comment by writemonkey** [comment]
done in 3.0.8.
i.
