### ISSUE TITLE
Disappearing Documents

### ISSUE THREAD

**Issue by nihilon** [writemonkey/wm3#61]
# The Issue
With multiple documents currently available, and one in the trash, if I change views in the Library side-bar, all the documents currently visible disappear and WM3 must be restarted to make them visible again.

# Context

1) Four documents under the "All" category, the most current of which was listed as having been edited 12 days ago.
2) One document in the trash.
3) Library side bar being visible initially does not appear to make a difference.

# Steps to reproduce

## Fresh start
1) Change the library view from "All" to "Today" or "Trash".
2) Change the library view back to "All". The document list will be empty.

## Notes

This issue can also be induced by finding any entry in the <code>writemonkey3_sheets</code> file that has a dtm or _dt that is within the last 12 days and removing it from the file manually. Once that is done, the behavior returns

# Workaround

Create a new document and save it or save a document to update it's last edited date.

**Comment by writemonkey** [comment]
This has been dealt with. Next beta with the fix will be available soon! Thanks.
i.
