### ISSUE TITLE
UI text very small in high res screen

### ISSUE THREAD

**Issue by sguergachi** [writemonkey/wm3#64]
I am on Windows 10 laptop running a 1080p res on a 12" laptop screen, this is what I see when I open the app (Beta 2):

![image](https://cloud.githubusercontent.com/assets/615386/19529868/9f73e41c-95ff-11e6-854f-bda74accf174.png)

It seems the labels used in the UI are a bit too small

My display is scaled to 125%

![image](https://cloud.githubusercontent.com/assets/615386/19529910/c1aead6e-95ff-11e6-9007-5f342432936d.png)

**Comment by writemonkey** [comment]
I see. This is one thing not yet addressed. Quick and dirty solution:

Open one of the theme files, find:

```
$wm-ui-document-pane {}
$wm-ui-project-pane {}
$wm-ui-module-pane {}
```

and add:

`zoom: 1.1!important;`

to all of them. Save the file and then select that theme in wm.

But this is not tested well!

i.

**Comment by nomad101** [comment]
The 'dirty' solution works well. Though when **editing** the repository, the text is small. Is there a hack to make it larger?

Thanks

**Comment by writemonkey** [comment]
Done. `Set User Interface Zoom` from command palette.
i.
