### ISSUE TITLE
Sounds not working

### ISSUE THREAD

**Issue by inkstain** [writemonkey/wm3#67]
Tried all sounds in turn as well as toggling sounds off and on and none are working as yet on Ubuntu 14.04

**Comment by writemonkey** [comment]
Can anyone on linux confirm that?

**Comment by inkstain** [comment]
This turned out to be a simple issue after all, I did not realize until I opened the handy developer console I saw errors such as:

`file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/key.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/key2.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/enter.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/delete.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/space.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/key.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/key2.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/enter.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/delete.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/laotsan/Apps/writemonkey3/plugins/clickClack/schemes/Old%20typewriter/space.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
`

But the files seemed to be there. Looking closer I saw the clickClack folder was in fact called ClickClack as is the case also with the Windows archive so the path references for the sound files in the code seem off on the linux version. As a workaround, I just renamed the folder to start with a lowercase 'c' and sounds are working fine

**Comment by writemonkey** [comment]
Thanks, you saved me time! Does white noises work ok too?
i.

**Comment by inkstain** [comment]
I didn't see your question until after I did a search& replace in click_clack.js to replace the string "clickClack" with "ClickClack" and renamed the folder back to the proper ClickClack. As of now, typing sounds and all whitenoise sounds I tested work perfectly

**Comment by writemonkey** [comment]
Thanks.
