### ISSUE TITLE
Save to export option

### ISSUE THREAD

**Issue by selfpublish** [writemonkey/wm3#68]
Iztok,

It would be great if you could add an option to export the document you are working on to an MD file in a specific directory every time you hit 'save.' The MD file in that folder would be overwritten each time you saved it.  Rather than having to manually export and save it each time.

The use scenario is the ability to quickly share a file I have been working on with a colleague.  As it is now, when you put the doc repository in dropbox, you can't have more than one instance open without creating a conflict (which I am sure you are well aware).

**I am loving WM3** - brilliant work! Thanks for the opportunity to test drive.

~Brian

**Comment by writemonkey** [comment]
Support for files is a whole new chapter I must address. WM3 will be able to open, save and export files. Also, there will be an option to bind database document to a file on disk, something similar you are proposing.

Yes, Dropbox option is problematic but this can be solved and conflicts eliminated even with 2 instances open at the same time.

And most importantly, I am glad you like wm3 so far.

i.
