### ISSUE TITLE
Error in smart functionality for lists

### ISSUE THREAD

**Issue by LThorburn** [writemonkey/wm3#78]
Say you have a list item like so:

    1. This is the first item.

If your cursor is at the start of the line (immediately before the `1`), and you hit enter, you will end up with this:

    2. 1. This is the first item.

Which is probably a bug? I think it would make more sense for it to simply insert a new line before the first item, and only add a new number if hitting enter from a cursor position within the list item itself.

There's similar behaviour for unordered lists and quotes.

**Comment by writemonkey** [comment]
Fixed.
