### ISSUE TITLE
Feature Request: Customisable command palette prompt

### ISSUE THREAD

**Issue by LThorburn** [writemonkey/wm3#79]
Really a very minor thing, but it would be nice if the command palette prompt `What do you wanna do?` that appears after deleting text from the search bar was customisable with a line in the settings file.

I'd like to either change it to `What do you want to do?` or simply remove it (set it to an empty string).

Also, thanks for all the work! I've just finished writing an essay for uni using WM3 and really enjoyed the experience.

**Comment by writemonkey** [comment]
The prompt was actually somehow cheesy and not necessary. Removed.
