### ISSUE TITLE
Typing sounds settings reset each time closed

### ISSUE THREAD

**Issue by novakwh** [writemonkey/wm3#82]
Typing sounds must be turned on every time the application is closed and reopened, unless I'm missing something. This seems like a bug to me -- a bit annoying to have to turn them on each time; old WriteMonkey always remembered the setting.

Loving wm3! Can't wait for the ability to create folders in the database and do some basic organization, that will be all I need to make it my go-to app for writing.

**Comment by writemonkey** [comment]
You are not missing anything. I'll make sounds persisting.
i.
