### ISSUE TITLE
Deleting a document  issue

### ISSUE THREAD

**Issue by StoryHack** [writemonkey/wm3#89]
When I move a document from that left pane to the trash by right clicking and saying "Move to Trash", sometimes the text from that window remains in the editor. This was most noticable to me when I deleted the last document in the database, and the text remained.

**Comment by writemonkey** [comment]
Thanks, I'll look into it.
i.

**Comment by writemonkey** [comment]
It seems the problem occurs when the last document on the list is deleted.
i.

**Comment by writemonkey** [comment]
fixed.
i.
