### ISSUE TITLE
Noticable and Steady CPU in pulseaudio on Linux - sounds not working

### ISSUE THREAD

**Issue by inkstain** [writemonkey/wm3#94]
on Ubuntu 14.04

With 3.0.3 beta 3, two processes of pulseaudio have each between 3.5 - 9 % CPU. Each stays within that range while WriteMonkey is open and shut when WM is closed. This happens regardless of whether sounds are enabled or not (I checked DevTools --> Resources --> Local Storage --> file:// to verify values change and enable/disable as I make the changes in Command Palette.

Likely related (so not opening a new case on this) is that none of the sounds (click or whitenoise) works. There was a previous issue with the last beta due to a misnamed folder in the plugins but that is not the case here. DevTool console shows no errors on loading modules.

**Comment by writemonkey** [comment]
I don't own linux machine and can't test this promptly. Is it possible to temporarily disable pulseaudio sound server? Does sounds work then?

9% for a process is of course far too much. Will look into it.

i.

**Comment by inkstain** [comment]
Okay some interesting findings on this:

 I used 'pasuspender' to envoke nw so that it would not utilize pulseaudio sound for that process and though the sound did not work within wm3 I noticed that the CPU usage of the nw process itself was noticably less. Before, it was consistent at 3% but now it is safely below 1% most of the time. On the previous beta, sound worked but with a much higher CPU on the writemonkey process (but no anomalous usage in pulseaudio). If it will be helpful, I can try to do a code comparison between the betas to see if I can isolate the difference there, not sure I will catch it as I know nothing about javascript but at least you can concentrate more on the Windows and OSX stuff in the meantime.

**Comment by writemonkey** [comment]
I haven't touched sound related code for this beta.
i.
